/* The following code was generated by JFlex 1.6.1 */

/*--------------------------------------------------
 ------------  1ra Area: Codigo de Usuario ---------
 ---------------------------------------------------*/

//------> Paquetes,importaciones
package Analizadores;
import java_cup.runtime.*;
import com.mycompany.proyecto1_2021s2.error;
import com.mycompany.proyecto1_2021s2.Ventana;
import com.mycompany.proyecto1_2021s2.Token;

/*----------------------------------------------------------
  ------------  2da Area: Opciones y Declaraciones ---------
  ----------------------------------------------------------*/

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/main/java/Analizadores/Analizador_Lexico.jflex</tt>
 */
public class Analizador_Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0, 48,  6, 50, 48,  9,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    49,  0,  5, 10, 17,  0,  0,  7, 22, 23, 11,  0, 16, 18,  2,  0, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 14, 15,  0, 21,  0,  0, 
     0, 26, 31, 30, 45, 38, 27, 24, 47, 29, 39,  4, 36, 46, 43, 37, 
    44,  4, 25, 33, 34, 35, 41,  4, 40, 42,  4, 19,  0, 20,  0,  8, 
     0, 26, 31, 30, 45, 38, 27, 24, 47, 29, 39,  4, 36, 46, 43, 37, 
    44,  4, 25, 33, 34, 35, 41,  4, 40, 42,  4, 12,  3, 13,  0,  0, 
     0,  0,  0,  0,  0, 50,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\1\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\3\3\1\1\6\3"+
    "\1\0\1\24\2\0\1\25\1\0\4\24\1\0\1\24"+
    "\1\0\6\24\1\26\2\27\2\25\2\0\4\24\1\0"+
    "\1\24\1\0\6\24\1\0\1\30\4\24\1\0\1\24"+
    "\1\0\1\24\1\31\3\24\1\0\1\24\1\0\2\24"+
    "\1\0\2\24\1\0\1\24\1\0\4\24\1\0\1\24"+
    "\1\0\2\24\1\0\2\24\2\32\2\33\2\24\1\34"+
    "\1\0\1\24\1\0\2\24\2\35\1\36\1\37\1\40"+
    "\1\37\1\40\2\41\1\24\1\0\1\24\3\0\6\24"+
    "\1\0\1\24\3\0\5\24\1\0\1\24\1\0\1\24"+
    "\2\0\1\42\2\24\1\42\2\24\1\0\1\24\1\0"+
    "\1\24\2\0\4\24\1\0\1\24\1\0\1\24\2\0"+
    "\4\24\1\0\1\24\1\0\1\24\1\43\1\44\1\43"+
    "\1\44\2\24\1\0\1\24\1\0\2\24\1\45\1\0"+
    "\1\24\1\0\2\24\1\0\1\24\2\46\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\2\47\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\2\50";

  private static int [] zzUnpackAction() {
    int [] result = new int[231];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\314\0\63\0\377\0\63"+
    "\0\u0132\0\63\0\63\0\63\0\63\0\63\0\63\0\63"+
    "\0\63\0\63\0\63\0\63\0\63\0\u0165\0\u0198\0\u01cb"+
    "\0\u01fe\0\u0231\0\u0264\0\u0297\0\u02ca\0\u02fd\0\u0330\0\u0363"+
    "\0\231\0\u0396\0\u03c9\0\u03fc\0\u042f\0\u0462\0\u0495\0\u04c8"+
    "\0\u04fb\0\u052e\0\u0561\0\u0594\0\u05c7\0\u05fa\0\u062d\0\u0660"+
    "\0\u0693\0\u06c6\0\u0363\0\63\0\u03c9\0\63\0\u06f9\0\u072c"+
    "\0\u075f\0\u0792\0\u07c5\0\u07f8\0\u082b\0\u085e\0\u0891\0\u08c4"+
    "\0\u08f7\0\u092a\0\u095d\0\u0990\0\u09c3\0\u09f6\0\u0a29\0\63"+
    "\0\u0a5c\0\u0a8f\0\u0ac2\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e\0\u0bc1"+
    "\0\231\0\u0bf4\0\u0c27\0\u0c5a\0\u0c8d\0\u0cc0\0\u0cf3\0\u0d26"+
    "\0\u0d59\0\u0d8c\0\u0dbf\0\u0df2\0\u0e25\0\u0e58\0\u0e8b\0\u0ebe"+
    "\0\u0ef1\0\u0f24\0\u0f57\0\u0f8a\0\u0fbd\0\u0ff0\0\u1023\0\u1056"+
    "\0\u1089\0\u10bc\0\u10ef\0\63\0\231\0\u1122\0\u1155\0\u1188"+
    "\0\u11bb\0\231\0\u11ee\0\u1221\0\u1254\0\u1287\0\u12ba\0\63"+
    "\0\231\0\231\0\63\0\63\0\231\0\231\0\63\0\231"+
    "\0\u12ed\0\u1320\0\u1353\0\u1386\0\u13b9\0\u13ec\0\u141f\0\u1452"+
    "\0\u1485\0\u14b8\0\u14eb\0\u151e\0\u1551\0\u1584\0\u15b7\0\u15ea"+
    "\0\u161d\0\u1650\0\u1683\0\u16b6\0\u16e9\0\u171c\0\u174f\0\u1782"+
    "\0\u17b5\0\u17e8\0\u181b\0\u184e\0\63\0\u1881\0\u18b4\0\231"+
    "\0\u18e7\0\u191a\0\u194d\0\u1980\0\u19b3\0\u19e6\0\u1a19\0\u1a4c"+
    "\0\u1a7f\0\u1ab2\0\u1ae5\0\u1b18\0\u1b4b\0\u1b7e\0\u1bb1\0\u1be4"+
    "\0\u1c17\0\u1c4a\0\u1c7d\0\u1cb0\0\u1ce3\0\u1d16\0\u1d49\0\u1d7c"+
    "\0\u1daf\0\u1de2\0\63\0\63\0\231\0\231\0\u1e15\0\u1e48"+
    "\0\u1e7b\0\u1eae\0\u1ee1\0\u1f14\0\u1f47\0\231\0\u1f7a\0\u1fad"+
    "\0\u1fe0\0\u2013\0\u2046\0\u2079\0\u20ac\0\63\0\231\0\u20df"+
    "\0\u2112\0\u2145\0\u2178\0\u21ab\0\u21de\0\63\0\231\0\u2211"+
    "\0\u2244\0\u2277\0\u22aa\0\u22dd\0\u2310\0\u2343\0\u2376\0\u23a9"+
    "\0\u23dc\0\u240f\0\u2442\0\u2475\0\u24a8\0\63\0\231";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[231];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\2\1\4\1\5\1\6\1\7\1\10"+
    "\1\6\1\11\1\2\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\4\1\27\1\4\1\2\1\4\1\30\1\4\1\31"+
    "\1\32\1\33\3\4\1\34\2\4\1\35\2\4\1\36"+
    "\1\37\2\4\2\6\65\0\1\3\1\40\61\0\1\41"+
    "\2\0\1\41\3\0\1\41\17\0\4\41\1\0\3\41"+
    "\1\0\17\41\3\0\5\42\2\0\54\42\5\43\2\0"+
    "\54\43\12\0\1\44\1\45\50\0\1\41\2\0\1\41"+
    "\3\0\1\41\17\0\1\41\1\46\2\41\1\0\3\41"+
    "\1\0\5\41\1\47\11\41\4\0\1\41\2\0\1\41"+
    "\3\0\1\41\17\0\1\41\1\50\2\41\1\0\3\41"+
    "\1\0\17\41\4\0\1\41\2\0\1\41\3\0\1\41"+
    "\17\0\4\41\1\0\3\41\1\0\4\41\1\51\12\41"+
    "\45\0\1\52\21\0\1\41\2\0\1\41\3\0\1\41"+
    "\17\0\4\41\1\0\3\41\1\0\1\41\1\53\15\41"+
    "\4\0\1\41\2\0\1\41\3\0\1\41\17\0\4\41"+
    "\1\54\1\55\2\41\1\0\17\41\4\0\1\41\2\0"+
    "\1\41\3\0\1\41\17\0\4\41\1\0\3\41\1\0"+
    "\6\41\1\56\10\41\4\0\1\41\2\0\1\41\3\0"+
    "\1\41\17\0\2\41\1\57\1\41\1\0\3\41\1\0"+
    "\17\41\4\0\1\41\2\0\1\41\3\0\1\41\17\0"+
    "\4\41\1\0\3\41\1\0\2\41\1\60\14\41\4\0"+
    "\1\41\2\0\1\41\3\0\1\41\17\0\4\41\1\0"+
    "\3\41\1\0\4\41\1\61\1\62\11\41\4\0\1\63"+
    "\1\0\1\63\55\0\1\63\1\0\5\42\1\64\1\0"+
    "\54\42\5\43\2\0\1\65\53\43\6\44\1\66\2\44"+
    "\1\67\51\44\13\70\1\71\47\70\1\0\1\41\2\0"+
    "\1\41\3\0\1\41\17\0\2\41\1\72\1\41\1\0"+
    "\3\41\1\0\17\41\4\0\1\41\2\0\1\41\3\0"+
    "\1\41\17\0\4\41\1\0\3\41\1\0\12\41\1\73"+
    "\4\41\4\0\1\41\2\0\1\41\3\0\1\41\17\0"+
    "\4\41\1\0\1\41\1\74\1\41\1\0\17\41\4\0"+
    "\1\41\2\0\1\41\3\0\1\41\17\0\4\41\1\0"+
    "\3\41\1\0\15\41\1\75\1\41\34\0\1\76\32\0"+
    "\1\41\2\0\1\41\3\0\1\41\17\0\1\41\1\77"+
    "\2\41\1\0\3\41\1\0\17\41\45\0\1\100\21\0"+
    "\1\41\2\0\1\41\3\0\1\41\17\0\4\41\1\0"+
    "\3\41\1\0\1\41\1\101\15\41\4\0\1\41\2\0"+
    "\1\41\3\0\1\41\17\0\4\41\1\0\3\41\1\0"+
    "\5\41\1\102\11\41\4\0\1\41\2\0\1\41\3\0"+
    "\1\41\17\0\4\41\1\0\3\41\1\0\3\41\1\103"+
    "\13\41\4\0\1\41\2\0\1\41\3\0\1\41\17\0"+
    "\4\41\1\0\3\41\1\0\12\41\1\104\4\41\4\0"+
    "\1\41\2\0\1\41\3\0\1\41\17\0\4\41\1\0"+
    "\3\41\1\0\2\41\1\105\14\41\4\0\1\41\2\0"+
    "\1\41\3\0\1\41\17\0\3\41\1\106\1\0\3\41"+
    "\1\0\17\41\11\0\1\66\54\0\13\70\1\107\47\70"+
    "\12\0\1\110\1\71\50\0\1\41\2\0\1\41\3\0"+
    "\1\41\17\0\3\41\1\111\1\0\3\41\1\0\17\41"+
    "\4\0\1\41\2\0\1\41\3\0\1\41\17\0\4\41"+
    "\1\0\3\41\1\0\5\41\1\112\11\41\4\0\1\41"+
    "\2\0\1\41\3\0\1\41\17\0\4\41\1\0\3\41"+
    "\1\0\16\41\1\113\4\0\1\41\2\0\1\41\3\0"+
    "\1\41\17\0\4\41\1\0\3\41\1\0\13\41\1\114"+
    "\3\41\37\0\2\115\26\0\1\41\2\0\1\41\3\0"+
    "\1\41\17\0\4\41\1\115\1\116\2\41\1\0\17\41"+
    "\46\0\1\117\20\0\1\41\2\0\1\41\3\0\1\41"+
    "\17\0\4\41\1\0\3\41\1\0\2\41\1\120\14\41"+
    "\4\0\1\41\2\0\1\41\3\0\1\41\17\0\4\41"+
    "\1\0\3\41\1\0\7\41\1\121\7\41\4\0\1\41"+
    "\2\0\1\41\3\0\1\41\17\0\4\41\1\0\3\41"+
    "\1\0\4\41\1\122\12\41\4\0\1\41\2\0\1\41"+
    "\3\0\1\41\17\0\4\41\1\0\3\41\1\0\1\41"+
    "\1\123\15\41\4\0\1\41\2\0\1\41\3\0\1\41"+
    "\17\0\4\41\1\0\2\41\1\124\1\0\17\41\4\0"+
    "\1\41\2\0\1\41\3\0\1\41\17\0\4\41\1\125"+
    "\1\126\2\41\1\0\17\41\3\0\12\70\1\110\1\107"+
    "\47\70\1\0\1\41\2\0\1\41\3\0\1\41\17\0"+
    "\4\41\1\127\1\130\2\41\1\0\17\41\4\0\1\41"+
    "\2\0\1\41\3\0\1\41\17\0\1\41\1\131\2\41"+
    "\1\0\3\41\1\0\17\41\4\0\1\41\2\0\1\41"+
    "\3\0\1\41\17\0\4\41\1\132\1\133\2\41\1\0"+
    "\17\41\4\0\1\41\2\0\1\41\3\0\1\41\17\0"+
    "\2\41\1\134\1\41\1\0\3\41\1\0\17\41\56\0"+
    "\1\135\10\0\1\41\2\0\1\41\3\0\1\41\17\0"+
    "\4\41\1\0\3\41\1\0\12\41\1\136\4\41\47\0"+
    "\1\137\17\0\1\41\2\0\1\41\3\0\1\41\17\0"+
    "\4\41\1\0\3\41\1\0\3\41\1\140\13\41\4\0"+
    "\1\41\2\0\1\41\3\0\1\41\17\0\1\41\1\141"+
    "\2\41\1\0\3\41\1\0\17\41\4\0\1\41\2\0"+
    "\1\41\3\0\1\41\17\0\2\41\1\142\1\41\1\0"+
    "\3\41\1\0\17\41\4\0\1\41\2\0\1\41\3\0"+
    "\1\41\17\0\4\41\1\0\3\41\1\0\3\41\1\143"+
    "\13\41\56\0\1\144\10\0\1\41\2\0\1\41\3\0"+
    "\1\41\17\0\4\41\1\0\3\41\1\0\12\41\1\145"+
    "\4\41\41\0\1\146\25\0\1\41\2\0\1\41\3\0"+
    "\1\41\17\0\4\41\1\0\1\41\1\147\1\41\1\0"+
    "\17\41\4\0\1\41\2\0\1\41\3\0\1\41\17\0"+
    "\2\41\1\150\1\41\1\0\3\41\1\0\17\41\54\0"+
    "\1\151\12\0\1\41\2\0\1\41\3\0\1\41\17\0"+
    "\4\41\1\0\3\41\1\0\10\41\1\152\6\41\4\0"+
    "\1\41\2\0\1\41\3\0\1\41\17\0\1\41\1\153"+
    "\2\41\1\0\3\41\1\0\17\41\33\0\1\154\33\0"+
    "\1\41\2\0\1\41\3\0\1\41\17\0\1\155\3\41"+
    "\1\0\3\41\1\0\17\41\50\0\1\156\16\0\1\41"+
    "\2\0\1\41\3\0\1\41\17\0\4\41\1\0\3\41"+
    "\1\0\4\41\1\157\12\41\4\0\1\41\2\0\1\41"+
    "\3\0\1\41\17\0\4\41\1\0\3\41\1\0\5\41"+
    "\1\160\11\41\4\0\1\41\2\0\1\41\3\0\1\41"+
    "\17\0\4\41\1\0\3\41\1\0\6\41\1\161\10\41"+
    "\4\0\1\41\2\0\1\41\3\0\1\41\17\0\4\41"+
    "\1\0\3\41\1\0\5\41\1\162\11\41\37\0\2\163"+
    "\26\0\1\41\2\0\1\41\3\0\1\41\17\0\4\41"+
    "\1\163\1\164\2\41\1\0\17\41\35\0\1\165\31\0"+
    "\1\41\2\0\1\41\3\0\1\41\17\0\2\41\1\166"+
    "\1\41\1\0\3\41\1\0\17\41\4\0\1\41\2\0"+
    "\1\41\3\0\1\41\17\0\1\41\1\167\2\41\1\0"+
    "\3\41\1\0\17\41\50\0\1\170\16\0\1\41\2\0"+
    "\1\41\3\0\1\41\17\0\4\41\1\0\3\41\1\0"+
    "\4\41\1\171\12\41\4\0\1\41\2\0\1\41\3\0"+
    "\1\41\17\0\4\41\1\0\3\41\1\0\5\41\1\172"+
    "\11\41\53\0\1\173\1\0\1\174\11\0\1\41\2\0"+
    "\1\41\3\0\1\41\17\0\4\41\1\0\3\41\1\0"+
    "\7\41\1\175\1\41\1\176\5\41\4\0\1\41\2\0"+
    "\1\41\3\0\1\41\17\0\4\41\1\0\3\41\1\177"+
    "\1\200\16\41\4\0\1\41\2\0\1\41\3\0\1\41"+
    "\17\0\4\41\1\0\3\41\1\0\5\41\1\201\11\41"+
    "\34\0\1\202\32\0\1\41\2\0\1\41\3\0\1\41"+
    "\17\0\1\41\1\203\2\41\1\0\3\41\1\0\17\41"+
    "\42\0\1\204\4\0\1\205\7\0\1\206\7\0\1\41"+
    "\2\0\1\41\3\0\1\41\17\0\4\41\1\0\2\41"+
    "\1\207\1\0\3\41\1\210\7\41\1\211\3\41\4\0"+
    "\1\41\2\0\1\41\3\0\1\41\17\0\1\41\1\212"+
    "\2\41\1\0\3\41\1\0\17\41\4\0\1\41\2\0"+
    "\1\41\3\0\1\41\17\0\1\213\3\41\1\0\3\41"+
    "\1\0\5\41\1\214\11\41\33\0\1\215\33\0\1\41"+
    "\2\0\1\41\3\0\1\41\17\0\1\216\3\41\1\0"+
    "\3\41\1\0\17\41\35\0\1\217\64\0\2\220\61\0"+
    "\2\221\26\0\1\41\2\0\1\41\3\0\1\41\17\0"+
    "\2\41\1\222\1\41\1\0\3\41\1\0\17\41\4\0"+
    "\1\41\2\0\1\41\3\0\1\41\17\0\4\41\1\220"+
    "\1\223\2\41\1\0\17\41\4\0\1\41\2\0\1\41"+
    "\3\0\1\41\17\0\4\41\1\221\1\224\2\41\1\0"+
    "\17\41\4\0\1\41\2\0\1\41\3\0\1\41\17\0"+
    "\4\41\1\0\3\41\1\0\5\41\1\225\11\41\4\0"+
    "\1\41\2\0\1\41\3\0\1\41\17\0\4\41\1\0"+
    "\3\41\1\0\5\41\1\226\11\41\4\0\1\41\2\0"+
    "\1\41\3\0\1\41\17\0\4\41\1\0\3\41\1\227"+
    "\1\230\16\41\47\0\1\231\17\0\1\41\2\0\1\41"+
    "\3\0\1\41\17\0\4\41\1\0\3\41\1\0\3\41"+
    "\1\232\13\41\34\0\1\233\104\0\1\234\55\0\1\235"+
    "\15\0\1\41\2\0\1\41\3\0\1\41\17\0\1\41"+
    "\1\236\2\41\1\0\3\41\1\0\17\41\4\0\1\41"+
    "\2\0\1\41\3\0\1\41\17\0\4\41\1\0\3\41"+
    "\1\0\12\41\1\237\4\41\4\0\1\41\2\0\1\41"+
    "\3\0\1\41\17\0\4\41\1\0\3\41\1\0\5\41"+
    "\1\240\11\41\4\0\1\41\2\0\1\41\3\0\1\41"+
    "\17\0\4\41\1\0\3\41\1\0\13\41\1\241\3\41"+
    "\4\0\1\41\2\0\1\41\3\0\1\41\17\0\4\41"+
    "\1\0\3\41\1\0\12\41\1\242\4\41\57\0\1\243"+
    "\7\0\1\41\2\0\1\41\3\0\1\41\17\0\4\41"+
    "\1\0\3\41\1\0\13\41\1\244\3\41\50\0\1\245"+
    "\16\0\1\41\2\0\1\41\3\0\1\41\17\0\4\41"+
    "\1\0\3\41\1\0\4\41\1\246\12\41\34\0\1\247"+
    "\77\0\1\250\15\0\1\41\2\0\1\41\3\0\1\41"+
    "\17\0\1\41\1\251\2\41\1\0\3\41\1\0\17\41"+
    "\4\0\1\41\2\0\1\41\3\0\1\41\17\0\4\41"+
    "\1\0\3\41\1\0\5\41\1\252\11\41\4\0\1\41"+
    "\2\0\1\41\3\0\1\41\17\0\4\41\1\0\3\41"+
    "\1\0\4\41\1\253\12\41\4\0\1\41\2\0\1\41"+
    "\3\0\1\41\17\0\4\41\1\0\3\41\1\0\5\41"+
    "\1\254\11\41\51\0\1\255\15\0\1\41\2\0\1\41"+
    "\3\0\1\41\17\0\4\41\1\0\3\41\1\0\5\41"+
    "\1\256\11\41\42\0\1\257\24\0\1\41\2\0\1\41"+
    "\3\0\1\41\17\0\4\41\1\0\2\41\1\260\1\0"+
    "\17\41\35\0\1\261\62\0\1\262\31\0\1\41\2\0"+
    "\1\41\3\0\1\41\17\0\2\41\1\263\1\41\1\0"+
    "\3\41\1\0\17\41\4\0\1\41\2\0\1\41\3\0"+
    "\1\41\17\0\2\41\1\264\1\41\1\0\3\41\1\0"+
    "\17\41\4\0\1\41\2\0\1\41\3\0\1\41\17\0"+
    "\1\41\1\265\2\41\1\0\3\41\1\0\17\41\4\0"+
    "\1\41\2\0\1\41\3\0\1\41\17\0\1\41\1\266"+
    "\2\41\1\0\3\41\1\0\17\41\41\0\1\267\25\0"+
    "\1\41\2\0\1\41\3\0\1\41\17\0\4\41\1\0"+
    "\1\41\1\270\1\41\1\0\17\41\35\0\1\271\31\0"+
    "\1\41\2\0\1\41\3\0\1\41\17\0\2\41\1\272"+
    "\1\41\1\0\3\41\1\0\17\41\43\0\2\273\61\0"+
    "\2\274\22\0\1\41\2\0\1\41\3\0\1\41\17\0"+
    "\4\41\1\0\3\41\1\273\1\275\16\41\4\0\1\41"+
    "\2\0\1\41\3\0\1\41\17\0\4\41\1\0\3\41"+
    "\1\274\1\276\16\41\4\0\1\41\2\0\1\41\3\0"+
    "\1\41\17\0\4\41\1\0\3\41\1\0\1\41\1\277"+
    "\15\41\4\0\1\41\2\0\1\41\3\0\1\41\17\0"+
    "\2\41\1\300\1\41\1\0\3\41\1\0\17\41\37\0"+
    "\2\301\26\0\1\41\2\0\1\41\3\0\1\41\17\0"+
    "\4\41\1\301\1\302\2\41\1\0\17\41\47\0\1\303"+
    "\17\0\1\41\2\0\1\41\3\0\1\41\17\0\4\41"+
    "\1\0\3\41\1\0\3\41\1\304\13\41\4\0\1\41"+
    "\2\0\1\41\3\0\1\41\17\0\4\41\1\0\3\41"+
    "\1\0\5\41\1\305\11\41\4\0\1\41\2\0\1\41"+
    "\3\0\1\41\17\0\4\41\1\0\3\41\1\0\3\41"+
    "\1\306\13\41\36\0\1\307\30\0\1\41\2\0\1\41"+
    "\3\0\1\41\17\0\3\41\1\310\1\0\3\41\1\0"+
    "\17\41\51\0\1\311\15\0\1\41\2\0\1\41\3\0"+
    "\1\41\17\0\4\41\1\0\3\41\1\0\5\41\1\312"+
    "\11\41\4\0\1\41\2\0\1\41\3\0\1\41\17\0"+
    "\4\41\1\0\3\41\1\0\5\41\1\313\11\41\37\0"+
    "\2\314\26\0\1\41\2\0\1\41\3\0\1\41\17\0"+
    "\4\41\1\314\1\315\2\41\1\0\17\41\43\0\2\316"+
    "\22\0\1\41\2\0\1\41\3\0\1\41\17\0\4\41"+
    "\1\0\3\41\1\316\1\317\16\41\4\0\1\41\2\0"+
    "\1\41\3\0\1\41\17\0\4\41\1\0\3\41\1\320"+
    "\1\321\16\41\41\0\1\322\25\0\1\41\2\0\1\41"+
    "\3\0\1\41\17\0\4\41\1\0\1\41\1\323\1\41"+
    "\1\0\17\41\45\0\1\324\21\0\1\41\2\0\1\41"+
    "\3\0\1\41\17\0\4\41\1\0\3\41\1\0\1\41"+
    "\1\325\15\41\50\0\1\326\16\0\1\41\2\0\1\41"+
    "\3\0\1\41\17\0\4\41\1\0\3\41\1\0\4\41"+
    "\1\327\12\41\35\0\1\330\31\0\1\41\2\0\1\41"+
    "\3\0\1\41\17\0\2\41\1\331\1\41\1\0\3\41"+
    "\1\0\17\41\60\0\1\332\6\0\1\41\2\0\1\41"+
    "\3\0\1\41\17\0\4\41\1\0\3\41\1\0\14\41"+
    "\1\333\2\41\37\0\2\334\26\0\1\41\2\0\1\41"+
    "\3\0\1\41\17\0\4\41\1\334\1\335\2\41\1\0"+
    "\17\41\43\0\2\336\22\0\1\41\2\0\1\41\3\0"+
    "\1\41\17\0\4\41\1\0\3\41\1\336\1\337\16\41"+
    "\45\0\1\340\21\0\1\41\2\0\1\41\3\0\1\41"+
    "\17\0\4\41\1\0\3\41\1\0\1\41\1\341\15\41"+
    "\37\0\2\342\26\0\1\41\2\0\1\41\3\0\1\41"+
    "\17\0\4\41\1\342\1\343\2\41\1\0\17\41\41\0"+
    "\1\344\25\0\1\41\2\0\1\41\3\0\1\41\17\0"+
    "\4\41\1\0\1\41\1\345\1\41\1\0\17\41\50\0"+
    "\1\346\16\0\1\41\2\0\1\41\3\0\1\41\17\0"+
    "\4\41\1\0\3\41\1\0\4\41\1\347\12\41\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9435];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\1\1\1\11\1\1\14\11"+
    "\12\1\1\0\1\1\2\0\1\1\1\0\4\1\1\0"+
    "\1\1\1\0\7\1\1\11\1\1\1\11\1\1\2\0"+
    "\4\1\1\0\1\1\1\0\6\1\1\0\1\11\4\1"+
    "\1\0\1\1\1\0\5\1\1\0\1\1\1\0\2\1"+
    "\1\0\2\1\1\0\1\1\1\0\4\1\1\0\1\1"+
    "\1\0\2\1\1\0\2\1\1\11\6\1\1\0\1\1"+
    "\1\0\2\1\1\11\2\1\2\11\2\1\1\11\2\1"+
    "\1\0\1\1\3\0\6\1\1\0\1\1\3\0\5\1"+
    "\1\0\1\1\1\0\1\1\2\0\1\11\5\1\1\0"+
    "\1\1\1\0\1\1\2\0\4\1\1\0\1\1\1\0"+
    "\1\1\2\0\4\1\1\0\1\1\1\0\1\1\2\11"+
    "\4\1\1\0\1\1\1\0\3\1\1\0\1\1\1\0"+
    "\2\1\1\0\1\1\1\11\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\11\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[231];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //----> Codigo de usuario en sintaxis java


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Analizador_Lexico(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(Simbolos.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Error Lexico FCA"+yytext()+" Linea "+yyline+" Columna "+yycolumn); 
                            error nuevo = new error("Error Lexico en FCA: ", yytext(), yyline, yycolumn);
                            Ventana.listaErrores.add(nuevo);
            }
          case 41: break;
          case 2: 
            { System.out.println("Reconocio "+yytext()+" numero");  
                        Token nuevoTk = new Token("Numero",yytext(), yyline, yycolumn);
                        Ventana.listaTokens.add(nuevoTk);
                        return new Symbol(Simbolos.numero, yycolumn, yyline, yytext());
            }
          case 42: break;
          case 3: 
            { System.out.println("Reconocio "+yytext()+" letra"); 
                        Token nuevoTk = new Token("Letra",yytext(), yyline, yycolumn);
                        Ventana.listaTokens.add(nuevoTk);
                        return new Symbol(Simbolos.letra, yycolumn, yyline, yytext());
            }
          case 43: break;
          case 4: 
            { System.out.println("Reconocio "+yytext()+" comilladoble");   
              Token nuevoTk = new Token("Comilla Doble",yytext(), yyline, yycolumn);
              Ventana.listaTokens.add(nuevoTk);
              return new Symbol(Simbolos.comilladoble, yycolumn, yyline, yytext());
            }
          case 44: break;
          case 5: 
            { /* Espacios en blanco, se ignoran */
            }
          case 45: break;
          case 6: 
            { System.out.println("Reconocio "+yytext()+" comillasimple");   
              Token nuevoTk = new Token("Comilla Simple",yytext(), yyline, yycolumn);
              Ventana.listaTokens.add(nuevoTk);
              return new Symbol(Simbolos.comillasimple, yycolumn, yyline, yytext());
            }
          case 46: break;
          case 7: 
            { System.out.println("Reconocio "+yytext()+" guionBajo");   
              Token nuevoTk = new Token("Guion Bajo",yytext(), yyline, yycolumn);
              Ventana.listaTokens.add(nuevoTk);
              return new Symbol(Simbolos.guionBajo, yycolumn, yyline, yytext());
            }
          case 47: break;
          case 8: 
            { System.out.println("Reconocio "+yytext()+" llaveabre");   
              Token nuevoTk = new Token("Llave Abre",yytext(), yyline, yycolumn);
              Ventana.listaTokens.add(nuevoTk);
              return new Symbol(Simbolos.llaveabre, yycolumn, yyline, yytext());
            }
          case 48: break;
          case 9: 
            { System.out.println("Reconocio "+yytext()+" llavecierra");   
              Token nuevoTk = new Token("Llave cierra",yytext(), yyline, yycolumn);
              Ventana.listaTokens.add(nuevoTk);
              return new Symbol(Simbolos.llavecierra, yycolumn, yyline, yytext());
            }
          case 49: break;
          case 10: 
            { System.out.println("Reconocio "+yytext()+" dospuntos");   
              Token nuevoTk = new Token("Dos puntos",yytext(), yyline, yycolumn);
              Ventana.listaTokens.add(nuevoTk);
              return new Symbol(Simbolos.dospuntos, yycolumn, yyline, yytext());
            }
          case 50: break;
          case 11: 
            { System.out.println("Reconocio "+yytext()+" puntoycoma");   
              Token nuevoTk = new Token("Punto y Coma",yytext(), yyline, yycolumn);
              Ventana.listaTokens.add(nuevoTk);
              return new Symbol(Simbolos.puntoycoma, yycolumn, yyline, yytext());
            }
          case 51: break;
          case 12: 
            { System.out.println("Reconocio "+yytext()+" coma");   
              Token nuevoTk = new Token("Coma",yytext(), yyline, yycolumn);
              Ventana.listaTokens.add(nuevoTk);
              return new Symbol(Simbolos.coma, yycolumn, yyline, yytext());
            }
          case 52: break;
          case 13: 
            { System.out.println("Reconocio "+yytext()+" dolar");   
              Token nuevoTk = new Token("Dolar",yytext(), yyline, yycolumn);
              Ventana.listaTokens.add(nuevoTk);
              return new Symbol(Simbolos.dolar, yycolumn, yyline, yytext());
            }
          case 53: break;
          case 14: 
            { System.out.println("Reconocio "+yytext()+" guion");   
              Token nuevoTk = new Token("Guion",yytext(), yyline, yycolumn);
              Ventana.listaTokens.add(nuevoTk);
              return new Symbol(Simbolos.guion, yycolumn, yyline, yytext());
            }
          case 54: break;
          case 15: 
            { System.out.println("Reconocio "+yytext()+" corcheteA");   
              Token nuevoTk = new Token("CorcheteA",yytext(), yyline, yycolumn);
              Ventana.listaTokens.add(nuevoTk);
              return new Symbol(Simbolos.corcheteA, yycolumn, yyline, yytext());
            }
          case 55: break;
          case 16: 
            { System.out.println("Reconocio "+yytext()+" corcheteC");   
              Token nuevoTk = new Token("CorcheteC",yytext(), yyline, yycolumn);
              Ventana.listaTokens.add(nuevoTk);
              return new Symbol(Simbolos.corcheteC, yycolumn, yyline, yytext());
            }
          case 56: break;
          case 17: 
            { System.out.println("Reconocio "+yytext()+" igual");   
              Token nuevoTk = new Token("Igual",yytext(), yyline, yycolumn);
              Ventana.listaTokens.add(nuevoTk);
              return new Symbol(Simbolos.igual, yycolumn, yyline, yytext());
            }
          case 57: break;
          case 18: 
            { System.out.println("Reconocio "+yytext()+" parentesisA");   
              Token nuevoTk = new Token("ParentesisA",yytext(), yyline, yycolumn);
              Ventana.listaTokens.add(nuevoTk);
              return new Symbol(Simbolos.parentesisA, yycolumn, yyline, yytext());
            }
          case 58: break;
          case 19: 
            { System.out.println("Reconocio "+yytext()+" parentesisC");  
              Token nuevoTk = new Token("ParentesisC",yytext(), yyline, yycolumn);
              Ventana.listaTokens.add(nuevoTk);
              return new Symbol(Simbolos.parentesisC, yycolumn, yyline, yytext());
            }
          case 59: break;
          case 20: 
            { System.out.println("Reconocio "+yytext()+" id"); 
                        Token nuevoTk = new Token("Identificador",yytext(), yyline, yycolumn);
                        Ventana.listaTokens.add(nuevoTk);
                        return new Symbol(Simbolos.id, yycolumn, yyline, yytext());
            }
          case 60: break;
          case 21: 
            { System.out.println("Comentario: "+yytext());
            }
          case 61: break;
          case 22: 
            { System.out.println("Reconocio "+yytext()+" decimal"); 
                        Token nuevoTk = new Token("Decimal",yytext(), yyline, yycolumn);
                        Ventana.listaTokens.add(nuevoTk);
                        return new Symbol(Simbolos.decimal, yycolumn, yyline, yytext());
            }
          case 62: break;
          case 23: 
            { System.out.println("Reconocio "+yytext()+" cadena"); 
                        Token nuevoTk = new Token("Cadena",yytext(), yyline, yycolumn);
                        Ventana.listaTokens.add(nuevoTk);
                        return new Symbol(Simbolos.cadena, yycolumn, yyline, yytext());
            }
          case 63: break;
          case 24: 
            { System.out.println("Comentario doble: "+yytext());
            }
          case 64: break;
          case 25: 
            { System.out.println("Reconocio "+yytext()+" ejeX");  
                        Token nuevoTk = new Token("EjeX",yytext(), yyline, yycolumn);
                        Ventana.listaTokens.add(nuevoTk);
                        return new Symbol(Simbolos.ejeX, yycolumn, yyline, yytext());
            }
          case 65: break;
          case 26: 
            { System.out.println("Reconocio "+yytext()+" string");  
                        Token nuevoTk = new Token("String",yytext(), yyline, yycolumn);
                        Ventana.listaTokens.add(nuevoTk);
                        return new Symbol(Simbolos.string, yycolumn, yyline, yytext());
            }
          case 66: break;
          case 27: 
            { System.out.println("Reconocio "+yytext()+" titulo");  
                        Token nuevoTk = new Token("Titulo",yytext(), yyline, yycolumn);
                        Ventana.listaTokens.add(nuevoTk);
                        return new Symbol(Simbolos.titulo, yycolumn, yyline, yytext());
            }
          case 67: break;
          case 28: 
            { System.out.println("Reconocio "+yytext()+" dou");  
                        Token nuevoTk = new Token("Double",yytext(), yyline, yycolumn);
                        Ventana.listaTokens.add(nuevoTk);
                        return new Symbol(Simbolos.dou, yycolumn, yyline, yytext());
            }
          case 68: break;
          case 29: 
            { System.out.println("Reconocio "+yytext()+" ar");  
                        Token nuevoTk = new Token("Archivo",yytext(), yyline, yycolumn);
                        Ventana.listaTokens.add(nuevoTk);
                        return new Symbol(Simbolos.ar, yycolumn, yyline, yytext());
            }
          case 69: break;
          case 30: 
            { System.out.println("Reconocio "+yytext()+" compare");  
                        Token nuevoTk = new Token("Compare",yytext(), yyline, yycolumn);
                        Ventana.listaTokens.add(nuevoTk);
                        return new Symbol(Simbolos.compare, yycolumn, yyline, yytext());
            }
          case 70: break;
          case 31: 
            { System.out.println("Reconocio "+yytext()+" tituloX");  
                        Token nuevoTk = new Token("Titulo X",yytext(), yyline, yycolumn);
                        Ventana.listaTokens.add(nuevoTk);
                        return new Symbol(Simbolos.tituloX, yycolumn, yyline, yytext());
            }
          case 71: break;
          case 32: 
            { System.out.println("Reconocio "+yytext()+" tituloY");  
                        Token nuevoTk = new Token("Titulo Y",yytext(), yyline, yycolumn);
                        Ventana.listaTokens.add(nuevoTk);
                        return new Symbol(Simbolos.tituloY, yycolumn, yyline, yytext());
            }
          case 72: break;
          case 33: 
            { System.out.println("Reconocio "+yytext()+" Valores");  
                        Token nuevoTk = new Token("Valores",yytext(), yyline, yycolumn);
                        Ventana.listaTokens.add(nuevoTk);
                        return new Symbol(Simbolos.Valores, yycolumn, yyline, yytext());
            }
          case 73: break;
          case 34: 
            { System.out.println("Reconocio "+yytext()+" graficaPie");  
                        Token nuevoTk = new Token("Grafia Pie",yytext(), yyline, yycolumn);
                        Ventana.listaTokens.add(nuevoTk);
                        return new Symbol(Simbolos.graficaPie, yycolumn, yyline, yytext());
            }
          case 74: break;
          case 35: 
            { System.out.println("Reconocio "+yytext()+" graficaBarras");  
                        Token nuevoTk = new Token("Grafica Barras",yytext(), yyline, yycolumn);
                        Ventana.listaTokens.add(nuevoTk);
                        return new Symbol(Simbolos.graficaBarras, yycolumn, yyline, yytext());
            }
          case 75: break;
          case 36: 
            { System.out.println("Reconocio "+yytext()+" graficaLineas");  
                        Token nuevoTk = new Token("Grafica Lineas",yytext(), yyline, yycolumn);
                        Ventana.listaTokens.add(nuevoTk);
                        return new Symbol(Simbolos.graficaLineas, yycolumn, yyline, yytext());
            }
          case 76: break;
          case 37: 
            { System.out.println("Reconocio "+yytext()+" PuntajeGeneral");  
                        Token nuevoTk = new Token("Puntaje General",yytext(), yyline, yycolumn);
                        Ventana.listaTokens.add(nuevoTk);
                        return new Symbol(Simbolos.PuntajeGeneral, yycolumn, yyline, yytext());
            }
          case 77: break;
          case 38: 
            { System.out.println("Reconocio "+yytext()+" DefinirGlobales");  
                        Token nuevoTk = new Token("Definir Globales",yytext(), yyline, yycolumn);
                        Ventana.listaTokens.add(nuevoTk);
                        return new Symbol(Simbolos.DefinirGlobales, yycolumn, yyline, yytext());
            }
          case 78: break;
          case 39: 
            { System.out.println("Reconocio "+yytext()+" PuntajeEspecifico");  
                        Token nuevoTk = new Token("Puntaje Especifico",yytext(), yyline, yycolumn);
                        Ventana.listaTokens.add(nuevoTk);
                        return new Symbol(Simbolos.PuntajeEspecifico, yycolumn, yyline, yytext());
            }
          case 79: break;
          case 40: 
            { System.out.println("Reconocio "+yytext()+" generarReporteEstadistico");  
                        Token nuevoTk = new Token("Generar Reporte Estadistico",yytext(), yyline, yycolumn);
                        Ventana.listaTokens.add(nuevoTk);
                        return new Symbol(Simbolos.generarReporteEstadistico, yycolumn, yyline, yytext());
            }
          case 80: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
