
/*--------------- 1ra Area: Codigo de Usuario -----------------------*/
//-------> importaciones, paquetes
package Analizadores;
import java_cup.runtime.Symbol;

import com.mycompany.proyecto1_2021s2.Ventana;
import com.mycompany.proyecto1_2021s2.error;

import javax.swing.JOptionPane;
import java.util.LinkedList;

import Reportes.Caracteristica;
import Reportes.GraficaBarras;
import Reportes.Valor;

//------> Codigo para el parser,variables, metodos
parser code{:

        public void syntax_error(Symbol s)
        {
            System.err.println("Error en la Linea " + (s.right+1) +" Columna "+(s.left+1)+ ". Identificador "+s.value + " no reconocido. Se ha recuperado del error." );
            error nuevo = new error("Error Sintactico (Recuperado)", s.value.toString(), s.right+1, s.left+1);
            Ventana.listaErrores.add(nuevo);
        }
        public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
        {
            System.err.println("Error en la Linea " + (s.right+1)+ " Columna "+(s.left+1)+". Identificador " +s.value + " no reconocido.");
            error nuevo = new error("Error Sintactico", s.value.toString(), s.right+1, s.left+1);
            Ventana.listaErrores.add(nuevo);
        }

 :}


//------> Codigo para las acciones gramaticales
action code
{:  :}

/*--------------- 2da Area: Declaraciones -----------------------*/

//------> declaracion de terminales 

terminal String llaveabre,llavecierra;
terminal String dospuntos,puntoycoma,coma,dolar;
terminal String comilladoble, comillasimple;
terminal String numero,cadena,id,decimal,letra;
terminal String guion,guionBajo;
terminal String parentesisC, parentesisA,igual,corcheteC,corcheteA;

terminal String graficaBarras,titulo,ejeX,Valores,tituloX,tituloY;

terminal String generarReporteEstadistico,compare;

terminal String graficaPie;

terminal String graficaLineas, ar;

terminal String DefinirGlobales,string,dou;



//------> declaracion de no terminales

non terminal  INICIO, GENERARREPORTE;
non terminal  INSTRUCCIONES,INSTRUCCION;
non terminal  COMPARE,DEFINIRGLOBALES,GRAFICABARRAS,GRAFICAPIE,GRAFICASLINEAS;
non terminal  DEFINICIONVARIABLESG,DEFINICIONVARIABLEG,TIPO,VALORTIPO;
non terminal  INFOSBARRAS;
non terminal  INFOSLINEAS;
non terminal  INFOS,DATOS,VALORES,DATO;

//------> precedencia de menor a mayor



start with INICIO;

/*--------------- 3ra Area: Reglas Semanticas -----------------------*/

INICIO::= GENERARREPORTE:a                                                                                {: :}
    ;

GENERARREPORTE::= generarReporteEstadistico:a  llaveabre:b INSTRUCCIONES:c  llavecierra:d                       {: :}
    ;

INSTRUCCIONES::=INSTRUCCIONES:a INSTRUCCION:b                                                               {: :}
    | INSTRUCCION:a                                                                                       {: :}
    ;

INSTRUCCION::= COMPARE:a                                                                                  {: :}
    |DEFINIRGLOBALES:a                                                                                    {: :}
    |GRAFICABARRAS:a                                                                                      {: :}
    |GRAFICAPIE:a                                                                                         {: :}
    |GRAFICASLINEAS:a                                                                                     {: :}
    ;

COMPARE::= compare:a parentesisA:b  cadena:c  coma:d   cadena:e   parentesisC:f  puntoycoma:g                         {: :}
    ;

DEFINIRGLOBALES::= DefinirGlobales:a llaveabre:b DEFINICIONVARIABLESG:c llavecierra:g                           {: :}
    ;

DEFINICIONVARIABLESG::= DEFINICIONVARIABLESG:a DEFINICIONVARIABLEG:b                                        {: :}
    |DEFINICIONVARIABLEG:a                                                                                {: :}
    ;

    
DEFINICIONVARIABLEG::= TIPO:a id:b igual:c VALORTIPO:d puntoycoma:e                                               {: :}
    ;

TIPO::= string:a                                                                                          {: :}
    | dou:a                                                                                               {: :}
    ;

VALORTIPO::= cadena:a                                                                                     {: :}
    |numero:a                                                                                             {: :}
    |decimal:a                                                                                            {: :}
    |dolar:a llaveabre:b id:c coma:d  cadena:e  coma:f cadena:g coma:h cadena:i llavecierra:j                               {: :}
    ;

GRAFICABARRAS::= graficaBarras:a llaveabre:b INFOSBARRAS:c llavecierra:d                                        {: :}
    ;

GRAFICASLINEAS::= graficaLineas:a llaveabre:b INFOSLINEAS:c  llavecierra:d                                      {: :}
    ;

GRAFICAPIE::= graficaPie:a llaveabre:b INFOS:c llavecierra:d                                                    {: :}
    ;

INFOSBARRAS::=INFOSBARRAS:a titulo:b dospuntos:c id:d puntoycoma:e                                                {: :}
    |INFOSBARRAS:a ejeX:b dospuntos:c corcheteA:d DATOS:e  corcheteC:f puntoycoma:g                                   {: :}
    |INFOSBARRAS:a VALORES:b                                                                                {: :}
    |INFOSBARRAS:a tituloX:b dospuntos:c  cadena:d  puntoycoma:e                                                  {: :}
    |INFOSBARRAS:a tituloY:b dospuntos:c  cadena:d  puntoycoma:e                                                  {: :}
    |titulo:a dospuntos:b id:c puntoycoma:d                                                                     {: :}
    |ejeX:a dospuntos:b corcheteA:c DATOS:d  corcheteC:e puntoycoma:f                                               {: :}
    |tituloX:a dospuntos:b  cadena:c  puntoycoma:d                                                              {: :}
    |tituloY:a dospuntos:b  cadena:c  puntoycoma:d                                                              {: :}
    |VALORES:a                                                                                            {: :}
    ;

INFOSLINEAS::=INFOSLINEAS:a titulo:b dospuntos:c id:d puntoycoma:e                                                {: :}
    |INFOSLINEAS:a ar:b dospuntos:c cadena:d puntoycoma:e                                                         {: :}
    |titulo:a dospuntos:b id:c puntoycoma:d                                                                     {: :}
    |ar:a dospuntos:b cadena:c puntoycoma:d                                                                     {: :}
    ;

INFOS::=INFOS:a titulo:b dospuntos:c id:d puntoycoma:e                                                            {: :}
    |INFOS:a ejeX:b dospuntos:c corcheteA:d DATOS:e  corcheteC:f puntoycoma:g                                         {: :}
    |INFOS:a VALORES:b                                                                                      {: :}
    |titulo:a dospuntos:b id:c puntoycoma:d                                                                     {: :}
    |ejeX:a dospuntos:b corcheteA:c DATOS:d  corcheteC:e puntoycoma:f                                               {: :}
    |VALORES:a                                                                                            {: :}
    ;

VALORES::= Valores:a dospuntos:b corcheteA:c DATOS:d  corcheteC:e puntoycoma:f                                      {: :}
    ;

DATOS::= DATOS:a coma:b DATO:c                                                                                {: :}
    |DATO:a                                                                                               {: :}
    ;

DATO::=decimal:a                                                                                          {: :}                                                                                         
    |numero:a
    |cadena:a                                                                                             {: :}
    |id:a                                                                                                 {: :}
    |dolar:a llaveabre:b id:c coma:d cadena:e coma:f cadena:g coma:h cadena:i llavecierra:j                                 {: :}
    ;