
/*--------------- 1ra Area: Codigo de Usuario -----------------------*/
//-------> importaciones, paquetes
package Analizadores;
import java_cup.runtime.Symbol;

import com.mycompany.proyecto1_2021s2.Ventana;
import com.mycompany.proyecto1_2021s2.error;
import com.mycompany.proyecto1_2021s2.Comparar;

import javax.swing.JOptionPane;
import java.util.LinkedList;

import Reportes.Caracteristica;
import Reportes.GraficaBarras;

import Reportes.Valor;
import com.mycompany.proyecto1_2021s2.Variables;

import Reportes.GraficaLineas;
import Reportes.GraficaPie;

//------> Codigo para el parser,variables, metodos
parser code{:
        public String resultado = "";
        public static LinkedList<Object> instrucciones;

        public void syntax_error(Symbol s)
        {
            System.err.println("Error en la Linea " + (s.right+1) +" Columna "+(s.left+1)+ ". Identificador "+s.value + " no reconocido. Se ha recuperado del error." );
            error nuevo = new error("Error Sintactico (Recuperado)", s.value.toString(), s.right+1, s.left+1);
            Ventana.listaErrores.add(nuevo);
        }
        public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
        {
            System.err.println("Error en la Linea " + (s.right+1)+ " Columna "+(s.left+1)+". Identificador " +s.value + " no reconocido.");
            error nuevo = new error("Error Sintactico", s.value.toString(), s.right+1, s.left+1);
            Ventana.listaErrores.add(nuevo);
        }

 :}


//------> Codigo para las acciones gramaticales
action code
{:  :}

/*--------------- 2da Area: Declaraciones -----------------------*/

//------> declaracion de terminales 

terminal String llaveabre,llavecierra;
terminal String dospuntos,puntoycoma,coma,dolar;
terminal String comilladoble, comillasimple;
terminal String numero,cadena,id,decimal,letra;
terminal String guion,guionBajo;
terminal String parentesisC, parentesisA,igual,corcheteC,corcheteA;

terminal String graficaBarras,titulo,ejeX,Valores,tituloX,tituloY;

terminal String generarReporteEstadistico,compare;

terminal String graficaPie;

terminal String graficaLineas, ar;

terminal String DefinirGlobales,string,dou;

terminal String PuntajeEspecifico,PuntajeGeneral;

//------> declaracion de no terminales

non terminal INICIO;
non terminal LinkedList<Object> INSTRUCCIONES, GENERARREPORTE;
non terminal Object INSTRUCCION;
non terminal Comparar COMPARE;
non terminal LinkedList<Variables> DEFINIRGLOBALES;
non terminal GraficaBarras GRAFICABARRAS;
non terminal GraficaPie GRAFICAPIE;
non terminal GraficaLineas GRAFICASLINEAS;
non terminal LinkedList<Variables> DEFINICIONVARIABLESG;
non terminal Caracteristica INFOBARRA,INFO,INFOLINEA;
non terminal LinkedList<Caracteristica> INFOSBARRAS,INFOS,INFOSLINEAS;

non terminal Valor DATO;
non terminal LinkedList<Valor> DATOS;

//------> precedencia de menor a mayor



start with INICIO;

/*--------------- 3ra Area: Reglas Semanticas -----------------------*/

INICIO::= GENERARREPORTE:a                                                                                {: instrucciones = a; :}
    ;

GENERARREPORTE::= generarReporteEstadistico:a  llaveabre:b INSTRUCCIONES:c  llavecierra:d                 {: RESULT= c; :}
    ;

INSTRUCCIONES::=INSTRUCCIONES:a INSTRUCCION:b                                                             {: RESULT = a; RESULT.add(b); :}
    | INSTRUCCION:a                                                                                       {: RESULT = new LinkedList<>(); RESULT.add(a); :}
    ;

INSTRUCCION::= COMPARE:a                                                                                  {: RESULT = a; :}
    |DEFINIRGLOBALES:a                                                                                    {: RESULT = a; :}
    |GRAFICABARRAS:a                                                                                      {: RESULT = a; :}
    |GRAFICAPIE:a                                                                                         {: RESULT = a; :}
    |GRAFICASLINEAS:a                                                                                     {: RESULT = a; :}
    ;

COMPARE::= compare:a parentesisA:b  cadena:c  coma:d   cadena:e   parentesisC:f  puntoycoma:g             {: RESULT = new Comparar(c.substring(1,c.length()-1),e.substring(1,e.length()-1)); :}
    ;



DEFINIRGLOBALES::= DefinirGlobales:a llaveabre:b DEFINICIONVARIABLESG:c llavecierra:g                     {: RESULT = c; :}
    ;

DEFINICIONVARIABLESG::= DEFINICIONVARIABLESG:a string:b id:c igual:d DATO:e puntoycoma:f                  {: RESULT = a; RESULT.add(new Variables(1, c, e)); :}
    |DEFINICIONVARIABLESG:a dou:b id:c igual:d DATO:e puntoycoma:f                                        {: RESULT = a; RESULT.add(new Variables(2, c, e)); :}
    |string:a id:b igual:c DATO:d puntoycoma:e                                                            {: RESULT = new LinkedList<>(); RESULT.add(new Variables(1, b, d)); :}
    |dou:a id:b igual:c DATO:d puntoycoma:e                                                               {: RESULT = new LinkedList<>(); RESULT.add(new Variables(2, b, d)); :}
    ;




GRAFICABARRAS::= graficaBarras:a llaveabre:b INFOSBARRAS:c llavecierra:d                                  {: RESULT = new GraficaBarras(c); :}
    ;

GRAFICASLINEAS::= graficaLineas:a llaveabre:b INFOSLINEAS:c  llavecierra:d                                {: RESULT = new GraficaLineas(c); :}
    ;

GRAFICAPIE::= graficaPie:a llaveabre:b INFOS:c llavecierra:d                                              {: RESULT = new GraficaPie(c); :}
    ;

INFOSBARRAS::=INFOSBARRAS:a INFOBARRA:b                                                                   {: RESULT = a; RESULT.add(b); :}
    |INFOBARRA:a                                                                                          {: RESULT = new LinkedList<>(); RESULT.add(a); :}
    ;


INFOBARRA::=titulo:a dospuntos:b DATO:c puntoycoma:d                                                      {: RESULT = new Caracteristica(0,c); :}
    |ejeX:a dospuntos:b corcheteA:c DATOS:d  corcheteC:e puntoycoma:f                                     {: RESULT = new Caracteristica(1,d); :}
    |Valores:a dospuntos:b corcheteA:c DATOS:d  corcheteC:e puntoycoma:f                                  {: RESULT = new Caracteristica(2,d); :}
    |tituloX:a dospuntos:b  DATO:c  puntoycoma:d                                                          {: RESULT = new Caracteristica(3,c); :}
    |tituloY:a dospuntos:b  DATO:c  puntoycoma:d                                                          {: RESULT = new Caracteristica(4,c); :}
    
    ;

INFOSLINEAS::=INFOSLINEAS:a INFOLINEA:b                                                                   {: RESULT = a; RESULT.add(b); :}
    |INFOLINEA:a                                                                                          {: RESULT = new LinkedList<>(); RESULT.add(a); :}
    ;

INFOLINEA::=titulo:a dospuntos:b DATO:c puntoycoma:d                                                      {: RESULT = new Caracteristica(0,c); :}
    |ar:a dospuntos:b DATO:c puntoycoma:d                                                                 {: RESULT = new Caracteristica(5,c);/*este id 5 es para el archivo de la grafica de lineas*/:}
    |Valores:a dospuntos:b corcheteA:c DATOS:d  corcheteC:e puntoycoma:f                                  {: RESULT = new Caracteristica(2,d); :}
    ;

INFOS::=INFOS:a INFO:b                                                                                    {: RESULT = a; RESULT.add(b); :}
    |INFO:a                                                                                               {: RESULT = new LinkedList<>(); RESULT.add(a); :}
    ;

INFO::=titulo:a dospuntos:b DATO:c puntoycoma:d                                                           {: RESULT = new Caracteristica(0,c); :}
    |ejeX:a dospuntos:b corcheteA:c DATOS:d  corcheteC:e puntoycoma:f                                     {: RESULT = new Caracteristica(1,d); :}
    |Valores:a dospuntos:b corcheteA:c DATOS:d  corcheteC:e puntoycoma:f                                  {: RESULT = new Caracteristica(2,d); :}
    ;

DATOS::= DATOS:a coma:b DATO:c                                                                            {: RESULT = a; RESULT.add(c); :}
    |DATO:a                                                                                               {: RESULT = new LinkedList<>(); RESULT.add(a); :}
    ;

DATO::=decimal:a                                                                                          {: RESULT = new Valor(1, new Double(a)); :}
    |numero:a                                                                                             {: RESULT = new Valor(2, new Integer(a)); :}
    |id:a                                                                                                 {: RESULT = new Valor(3, a); :}
    |cadena:a                                                                                             {: RESULT = new Valor(4, a.substring(1,a.length()-1)); :}
    |dolar:a llaveabre:b PuntajeEspecifico:c coma:d cadena:e coma:f cadena:g coma:h cadena:i llavecierra:j{: RESULT = new Valor(5, e.substring(1,e.length()-1), g.substring(1,g.length()-1), i.substring(1,i.length()-1) ); :}
    |PuntajeEspecifico:a                                                                                  {: RESULT = new Valor(3, a); :}
    |PuntajeGeneral:a                                                                                     {: RESULT = new Valor(3, a); :}
    ;
