
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int tituloY = 27;
  public static final int graficaPie = 30;
  public static final int tituloX = 26;
  public static final int graficaBarras = 22;
  public static final int ar = 32;
  public static final int corcheteC = 20;
  public static final int PuntajeGeneral = 37;
  public static final int DefinirGlobales = 33;
  public static final int llaveabre = 2;
  public static final int corcheteA = 21;
  public static final int compare = 29;
  public static final int coma = 6;
  public static final int igual = 19;
  public static final int letra = 14;
  public static final int string = 34;
  public static final int generarReporteEstadistico = 28;
  public static final int guion = 15;
  public static final int ejeX = 24;
  public static final int puntoycoma = 5;
  public static final int comillasimple = 9;
  public static final int numero = 10;
  public static final int EOF = 0;
  public static final int comilladoble = 8;
  public static final int error = 1;
  public static final int PuntajeEspecifico = 36;
  public static final int guionBajo = 16;
  public static final int dospuntos = 4;
  public static final int id = 12;
  public static final int llavecierra = 3;
  public static final int titulo = 23;
  public static final int dolar = 7;
  public static final int parentesisC = 17;
  public static final int parentesisA = 18;
  public static final int Valores = 25;
  public static final int dou = 35;
  public static final int graficaLineas = 31;
  public static final int decimal = 13;
  public static final int cadena = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "llaveabre",
  "llavecierra",
  "dospuntos",
  "puntoycoma",
  "coma",
  "dolar",
  "comilladoble",
  "comillasimple",
  "numero",
  "cadena",
  "id",
  "decimal",
  "letra",
  "guion",
  "guionBajo",
  "parentesisC",
  "parentesisA",
  "igual",
  "corcheteC",
  "corcheteA",
  "graficaBarras",
  "titulo",
  "ejeX",
  "Valores",
  "tituloX",
  "tituloY",
  "generarReporteEstadistico",
  "compare",
  "graficaPie",
  "graficaLineas",
  "ar",
  "DefinirGlobales",
  "string",
  "dou",
  "PuntajeEspecifico",
  "PuntajeGeneral"
  };
}

