/* The following code was generated by JFlex 1.6.1 */

/*--------------------------------------------------
 ------------  1ra Area: Codigo de Usuario ---------
 ---------------------------------------------------*/

//------> Paquetes,importaciones
package AnalizadoresJS;
import java_cup.runtime.*;


/*----------------------------------------------------------
  ------------  2da Area: Opciones y Declaraciones ---------
  ----------------------------------------------------------*/

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/main/java/AnalizadoresJS/ALexico.jflex</tt>
 */
public class ALexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
    12, 12, 12, 12, 12, 12, 12, 12, 12, 51,  6, 52, 51,  9, 12, 12, 
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
    50, 12,  5, 10, 19, 12, 12,  7, 24, 25, 11, 12, 18, 20,  2, 12, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 16, 17, 12, 23, 12, 12, 
    12, 28, 33, 32, 47, 40, 29, 26, 49, 31, 41, 13, 38, 48, 45, 39, 
    46, 13, 27, 35, 36, 37, 43, 13, 42, 44, 13, 21, 12, 22, 12,  8, 
    12, 28, 33, 32, 47, 40, 29, 26, 49, 31, 41, 13, 38, 48, 45, 39, 
    46, 13, 27, 35, 36, 37, 43, 13, 42, 44, 13, 14,  3, 15, 12, 12, 
    12, 12, 12, 12, 12, 52, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
    12, 13, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
    12, 12, 12, 13, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\2\1\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\3\3\1\1\5\3"+
    "\1\0\1\24\3\0\1\25\4\24\1\0\1\24\1\0"+
    "\5\24\1\26\2\27\1\30\3\25\4\24\1\0\1\24"+
    "\1\0\5\24\3\30\2\25\4\24\1\0\1\24\1\0"+
    "\1\24\1\31\2\24\1\0\1\24\2\30\1\0\2\24"+
    "\1\0\2\24\1\0\1\24\1\0\3\24\1\0\1\24"+
    "\1\0\2\24\1\0\2\24\2\32\2\33\1\24\1\34"+
    "\1\0\1\24\1\0\2\24\2\35\1\36\1\37\1\40"+
    "\1\37\1\40\2\41\1\0\1\24\3\0\4\24\1\0"+
    "\1\24\3\0\4\24\1\0\1\24\2\0\1\42\2\24"+
    "\1\42\1\24\1\0\1\24\2\0\3\24\1\0\1\24"+
    "\2\0\3\24\1\0\1\24\1\43\1\44\1\43\1\44"+
    "\1\24\1\0\2\24\1\0\2\24\2\45\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\2\46";

  private static int [] zzUnpackAction() {
    int [] result = new int[205];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\330\0\66\0\u010e\0\66"+
    "\0\u0144\0\u017a\0\66\0\66\0\66\0\66\0\66\0\66"+
    "\0\66\0\66\0\66\0\66\0\66\0\66\0\u01b0\0\u01e6"+
    "\0\u021c\0\u0252\0\u0288\0\u02be\0\u02f4\0\u032a\0\u0360\0\u0396"+
    "\0\242\0\u03cc\0\u0402\0\u0438\0\u046e\0\u04a4\0\u04da\0\u0510"+
    "\0\u0546\0\u057c\0\u05b2\0\u05e8\0\u061e\0\u0654\0\u068a\0\u06c0"+
    "\0\u06f6\0\u0396\0\66\0\u0402\0\u072c\0\u0762\0\u0438\0\u0798"+
    "\0\u07ce\0\u0804\0\u083a\0\u0870\0\u08a6\0\u08dc\0\u0912\0\u0948"+
    "\0\u097e\0\u09b4\0\u09ea\0\u0a20\0\u0a56\0\u0438\0\u0a8c\0\66"+
    "\0\u0ac2\0\u0af8\0\u0b2e\0\u0b64\0\u0b9a\0\u0bd0\0\u0c06\0\u0c3c"+
    "\0\u0c72\0\242\0\u0ca8\0\u0cde\0\u0d14\0\u0d4a\0\66\0\u0d80"+
    "\0\u0db6\0\u0dec\0\u0e22\0\u0e58\0\u0e8e\0\u0ec4\0\u0efa\0\u0f30"+
    "\0\u0f66\0\u0f9c\0\u0fd2\0\u1008\0\u103e\0\u1074\0\u10aa\0\u10e0"+
    "\0\u1116\0\u114c\0\u1182\0\u11b8\0\66\0\242\0\u11ee\0\u1224"+
    "\0\u125a\0\242\0\u1290\0\u12c6\0\u12fc\0\u1332\0\u1368\0\66"+
    "\0\242\0\242\0\66\0\66\0\242\0\242\0\66\0\242"+
    "\0\u139e\0\u13d4\0\u140a\0\u1440\0\u1476\0\u14ac\0\u14e2\0\u1518"+
    "\0\u154e\0\u1584\0\u15ba\0\u15f0\0\u1626\0\u165c\0\u1692\0\u16c8"+
    "\0\u16fe\0\u1734\0\u176a\0\u17a0\0\u17d6\0\u180c\0\66\0\u1842"+
    "\0\u1878\0\242\0\u18ae\0\u18e4\0\u191a\0\u1950\0\u1986\0\u19bc"+
    "\0\u19f2\0\u1a28\0\u1a5e\0\u1a94\0\u1aca\0\u1b00\0\u1b36\0\u1b6c"+
    "\0\u1ba2\0\u1bd8\0\u1c0e\0\66\0\66\0\242\0\242\0\u1c44"+
    "\0\u1c7a\0\u1cb0\0\u1ce6\0\u1d1c\0\u1d52\0\u1d88\0\66\0\242"+
    "\0\u1dbe\0\u1df4\0\u1e2a\0\u1e60\0\u1e96\0\u1ecc\0\u1f02\0\u1f38"+
    "\0\u1f6e\0\u1fa4\0\u1fda\0\u2010\0\u2046\0\u207c\0\u20b2\0\u20e8"+
    "\0\u211e\0\u2154\0\u218a\0\66\0\242";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[205];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\2\1\4\1\5\1\6\1\7\1\10"+
    "\1\6\1\11\1\12\1\2\1\4\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\4\1\30\1\4\1\2\1\4\1\31"+
    "\1\4\1\32\1\33\1\34\3\4\1\35\2\4\1\36"+
    "\3\4\1\37\2\4\2\6\71\0\1\3\1\40\64\0"+
    "\1\41\2\0\1\41\3\0\1\41\4\0\1\41\14\0"+
    "\4\41\1\0\3\41\1\0\17\41\4\0\5\42\2\0"+
    "\57\42\5\43\2\0\57\43\1\0\3\44\1\0\5\44"+
    "\1\45\23\44\1\0\3\44\1\0\22\44\2\0\3\44"+
    "\1\0\31\44\1\0\3\44\1\0\22\44\2\0\1\41"+
    "\2\0\1\41\3\0\1\41\4\0\1\41\14\0\1\41"+
    "\1\46\2\41\1\0\3\41\1\0\5\41\1\47\11\41"+
    "\5\0\1\41\2\0\1\41\3\0\1\41\4\0\1\41"+
    "\14\0\1\41\1\50\2\41\1\0\3\41\1\0\17\41"+
    "\5\0\1\41\2\0\1\41\3\0\1\41\4\0\1\41"+
    "\14\0\4\41\1\0\3\41\1\0\4\41\1\51\12\41"+
    "\50\0\1\52\22\0\1\41\2\0\1\41\3\0\1\41"+
    "\4\0\1\41\14\0\4\41\1\0\3\41\1\0\1\41"+
    "\1\53\15\41\5\0\1\41\2\0\1\41\3\0\1\41"+
    "\4\0\1\41\14\0\4\41\1\54\1\55\2\41\1\0"+
    "\17\41\5\0\1\41\2\0\1\41\3\0\1\41\4\0"+
    "\1\41\14\0\4\41\1\0\3\41\1\0\6\41\1\56"+
    "\10\41\5\0\1\41\2\0\1\41\3\0\1\41\4\0"+
    "\1\41\14\0\2\41\1\57\1\41\1\0\3\41\1\0"+
    "\17\41\5\0\1\41\2\0\1\41\3\0\1\41\4\0"+
    "\1\41\14\0\4\41\1\0\3\41\1\0\4\41\1\60"+
    "\1\61\11\41\5\0\1\62\1\0\1\62\56\0\1\62"+
    "\3\0\5\42\1\63\1\0\57\42\5\43\2\0\1\64"+
    "\56\43\1\0\3\44\1\0\5\44\2\65\22\44\1\0"+
    "\3\44\1\0\22\44\1\0\1\66\3\45\1\66\1\45"+
    "\1\67\2\45\1\70\24\45\1\66\3\45\1\66\22\45"+
    "\1\66\1\0\1\41\2\0\1\41\3\0\1\41\4\0"+
    "\1\41\14\0\2\41\1\71\1\41\1\0\3\41\1\0"+
    "\17\41\5\0\1\41\2\0\1\41\3\0\1\41\4\0"+
    "\1\41\14\0\1\41\1\72\2\41\1\0\3\41\1\0"+
    "\17\41\5\0\1\41\2\0\1\41\3\0\1\41\4\0"+
    "\1\41\14\0\4\41\1\0\1\41\1\73\1\41\1\0"+
    "\17\41\5\0\1\41\2\0\1\41\3\0\1\41\4\0"+
    "\1\41\14\0\4\41\1\0\3\41\1\0\15\41\1\74"+
    "\1\41\37\0\1\75\33\0\1\41\2\0\1\41\3\0"+
    "\1\41\4\0\1\41\14\0\1\41\1\76\2\41\1\0"+
    "\3\41\1\0\17\41\50\0\1\77\22\0\1\41\2\0"+
    "\1\41\3\0\1\41\4\0\1\41\14\0\4\41\1\0"+
    "\3\41\1\0\1\41\1\100\15\41\5\0\1\41\2\0"+
    "\1\41\3\0\1\41\4\0\1\41\14\0\4\41\1\0"+
    "\3\41\1\0\5\41\1\101\11\41\5\0\1\41\2\0"+
    "\1\41\3\0\1\41\4\0\1\41\14\0\4\41\1\0"+
    "\3\41\1\0\3\41\1\102\13\41\5\0\1\41\2\0"+
    "\1\41\3\0\1\41\4\0\1\41\14\0\4\41\1\0"+
    "\3\41\1\0\2\41\1\103\14\41\5\0\1\41\2\0"+
    "\1\41\3\0\1\41\4\0\1\41\14\0\3\41\1\104"+
    "\1\0\3\41\1\0\17\41\4\0\1\105\3\65\1\105"+
    "\1\65\1\106\2\65\1\107\24\65\1\105\3\65\1\105"+
    "\22\65\1\105\6\66\1\110\2\66\1\111\54\66\1\0"+
    "\3\44\1\0\1\44\1\67\3\44\2\65\22\44\1\0"+
    "\3\44\1\0\22\44\2\0\1\41\2\0\1\41\3\0"+
    "\1\41\4\0\1\41\14\0\3\41\1\112\1\0\3\41"+
    "\1\0\17\41\5\0\1\41\2\0\1\41\3\0\1\41"+
    "\4\0\1\41\14\0\4\41\1\0\3\41\1\0\12\41"+
    "\1\113\4\41\5\0\1\41\2\0\1\41\3\0\1\41"+
    "\4\0\1\41\14\0\4\41\1\0\3\41\1\0\16\41"+
    "\1\114\5\0\1\41\2\0\1\41\3\0\1\41\4\0"+
    "\1\41\14\0\4\41\1\0\3\41\1\0\13\41\1\115"+
    "\3\41\42\0\2\116\27\0\1\41\2\0\1\41\3\0"+
    "\1\41\4\0\1\41\14\0\4\41\1\116\1\117\2\41"+
    "\1\0\17\41\51\0\1\120\21\0\1\41\2\0\1\41"+
    "\3\0\1\41\4\0\1\41\14\0\4\41\1\0\3\41"+
    "\1\0\2\41\1\121\14\41\5\0\1\41\2\0\1\41"+
    "\3\0\1\41\4\0\1\41\14\0\4\41\1\0\3\41"+
    "\1\0\7\41\1\122\7\41\5\0\1\41\2\0\1\41"+
    "\3\0\1\41\4\0\1\41\14\0\4\41\1\0\3\41"+
    "\1\0\4\41\1\123\12\41\5\0\1\41\2\0\1\41"+
    "\3\0\1\41\4\0\1\41\14\0\4\41\1\0\2\41"+
    "\1\124\1\0\17\41\5\0\1\41\2\0\1\41\3\0"+
    "\1\41\4\0\1\41\14\0\4\41\1\125\1\126\2\41"+
    "\1\0\17\41\4\0\6\105\1\127\2\105\1\130\54\105"+
    "\1\0\3\44\1\0\1\44\1\106\3\44\2\65\22\44"+
    "\1\0\3\44\1\0\22\44\7\0\1\110\60\0\1\41"+
    "\2\0\1\41\3\0\1\41\4\0\1\41\14\0\4\41"+
    "\1\131\1\132\2\41\1\0\17\41\5\0\1\41\2\0"+
    "\1\41\3\0\1\41\4\0\1\41\14\0\4\41\1\0"+
    "\3\41\1\0\5\41\1\133\11\41\5\0\1\41\2\0"+
    "\1\41\3\0\1\41\4\0\1\41\14\0\4\41\1\134"+
    "\1\135\2\41\1\0\17\41\5\0\1\41\2\0\1\41"+
    "\3\0\1\41\4\0\1\41\14\0\2\41\1\136\1\41"+
    "\1\0\3\41\1\0\17\41\61\0\1\137\11\0\1\41"+
    "\2\0\1\41\3\0\1\41\4\0\1\41\14\0\4\41"+
    "\1\0\3\41\1\0\12\41\1\140\4\41\52\0\1\141"+
    "\20\0\1\41\2\0\1\41\3\0\1\41\4\0\1\41"+
    "\14\0\4\41\1\0\3\41\1\0\3\41\1\142\13\41"+
    "\5\0\1\41\2\0\1\41\3\0\1\41\4\0\1\41"+
    "\14\0\1\41\1\143\2\41\1\0\3\41\1\0\17\41"+
    "\5\0\1\41\2\0\1\41\3\0\1\41\4\0\1\41"+
    "\14\0\4\41\1\0\3\41\1\0\3\41\1\144\13\41"+
    "\61\0\1\145\11\0\1\41\2\0\1\41\3\0\1\41"+
    "\4\0\1\41\14\0\4\41\1\0\3\41\1\0\12\41"+
    "\1\146\4\41\12\0\1\127\117\0\1\147\26\0\1\41"+
    "\2\0\1\41\3\0\1\41\4\0\1\41\14\0\4\41"+
    "\1\0\1\41\1\150\1\41\1\0\17\41\5\0\1\41"+
    "\2\0\1\41\3\0\1\41\4\0\1\41\14\0\1\41"+
    "\1\151\2\41\1\0\3\41\1\0\17\41\57\0\1\152"+
    "\13\0\1\41\2\0\1\41\3\0\1\41\4\0\1\41"+
    "\14\0\4\41\1\0\3\41\1\0\10\41\1\153\6\41"+
    "\5\0\1\41\2\0\1\41\3\0\1\41\4\0\1\41"+
    "\14\0\1\41\1\154\2\41\1\0\3\41\1\0\17\41"+
    "\36\0\1\155\34\0\1\41\2\0\1\41\3\0\1\41"+
    "\4\0\1\41\14\0\1\156\3\41\1\0\3\41\1\0"+
    "\17\41\53\0\1\157\17\0\1\41\2\0\1\41\3\0"+
    "\1\41\4\0\1\41\14\0\4\41\1\0\3\41\1\0"+
    "\4\41\1\160\12\41\5\0\1\41\2\0\1\41\3\0"+
    "\1\41\4\0\1\41\14\0\4\41\1\0\3\41\1\0"+
    "\5\41\1\161\11\41\5\0\1\41\2\0\1\41\3\0"+
    "\1\41\4\0\1\41\14\0\4\41\1\0\3\41\1\0"+
    "\5\41\1\162\11\41\42\0\2\163\27\0\1\41\2\0"+
    "\1\41\3\0\1\41\4\0\1\41\14\0\4\41\1\163"+
    "\1\164\2\41\1\0\17\41\40\0\1\165\32\0\1\41"+
    "\2\0\1\41\3\0\1\41\4\0\1\41\14\0\2\41"+
    "\1\166\1\41\1\0\3\41\1\0\17\41\5\0\1\41"+
    "\2\0\1\41\3\0\1\41\4\0\1\41\14\0\2\41"+
    "\1\167\1\41\1\0\3\41\1\0\17\41\53\0\1\170"+
    "\17\0\1\41\2\0\1\41\3\0\1\41\4\0\1\41"+
    "\14\0\4\41\1\0\3\41\1\0\4\41\1\171\12\41"+
    "\5\0\1\41\2\0\1\41\3\0\1\41\4\0\1\41"+
    "\14\0\4\41\1\0\3\41\1\0\5\41\1\172\11\41"+
    "\56\0\1\173\1\0\1\174\12\0\1\41\2\0\1\41"+
    "\3\0\1\41\4\0\1\41\14\0\4\41\1\0\3\41"+
    "\1\0\7\41\1\175\1\41\1\176\5\41\5\0\1\41"+
    "\2\0\1\41\3\0\1\41\4\0\1\41\14\0\4\41"+
    "\1\0\3\41\1\177\1\200\16\41\37\0\1\201\33\0"+
    "\1\41\2\0\1\41\3\0\1\41\4\0\1\41\14\0"+
    "\1\41\1\202\2\41\1\0\3\41\1\0\17\41\45\0"+
    "\1\203\4\0\1\204\7\0\1\205\10\0\1\41\2\0"+
    "\1\41\3\0\1\41\4\0\1\41\14\0\4\41\1\0"+
    "\2\41\1\206\1\0\3\41\1\207\7\41\1\210\3\41"+
    "\5\0\1\41\2\0\1\41\3\0\1\41\4\0\1\41"+
    "\14\0\1\41\1\211\2\41\1\0\3\41\1\0\17\41"+
    "\36\0\1\212\34\0\1\41\2\0\1\41\3\0\1\41"+
    "\4\0\1\41\14\0\1\213\3\41\1\0\3\41\1\0"+
    "\17\41\40\0\1\214\67\0\2\215\64\0\2\216\27\0"+
    "\1\41\2\0\1\41\3\0\1\41\4\0\1\41\14\0"+
    "\2\41\1\217\1\41\1\0\3\41\1\0\17\41\5\0"+
    "\1\41\2\0\1\41\3\0\1\41\4\0\1\41\14\0"+
    "\4\41\1\215\1\220\2\41\1\0\17\41\5\0\1\41"+
    "\2\0\1\41\3\0\1\41\4\0\1\41\14\0\4\41"+
    "\1\216\1\221\2\41\1\0\17\41\5\0\1\41\2\0"+
    "\1\41\3\0\1\41\4\0\1\41\14\0\1\41\1\222"+
    "\2\41\1\0\3\41\1\0\17\41\52\0\1\223\20\0"+
    "\1\41\2\0\1\41\3\0\1\41\4\0\1\41\14\0"+
    "\4\41\1\0\3\41\1\0\3\41\1\224\13\41\37\0"+
    "\1\225\107\0\1\226\60\0\1\227\16\0\1\41\2\0"+
    "\1\41\3\0\1\41\4\0\1\41\14\0\1\41\1\230"+
    "\2\41\1\0\3\41\1\0\17\41\5\0\1\41\2\0"+
    "\1\41\3\0\1\41\4\0\1\41\14\0\4\41\1\0"+
    "\3\41\1\0\12\41\1\231\4\41\5\0\1\41\2\0"+
    "\1\41\3\0\1\41\4\0\1\41\14\0\4\41\1\0"+
    "\3\41\1\0\5\41\1\232\11\41\5\0\1\41\2\0"+
    "\1\41\3\0\1\41\4\0\1\41\14\0\4\41\1\0"+
    "\3\41\1\0\5\41\1\233\11\41\53\0\1\234\17\0"+
    "\1\41\2\0\1\41\3\0\1\41\4\0\1\41\14\0"+
    "\4\41\1\0\3\41\1\0\4\41\1\235\12\41\37\0"+
    "\1\236\102\0\1\237\16\0\1\41\2\0\1\41\3\0"+
    "\1\41\4\0\1\41\14\0\1\41\1\240\2\41\1\0"+
    "\3\41\1\0\17\41\5\0\1\41\2\0\1\41\3\0"+
    "\1\41\4\0\1\41\14\0\4\41\1\0\3\41\1\0"+
    "\5\41\1\241\11\41\5\0\1\41\2\0\1\41\3\0"+
    "\1\41\4\0\1\41\14\0\4\41\1\0\3\41\1\0"+
    "\13\41\1\242\3\41\45\0\1\243\25\0\1\41\2\0"+
    "\1\41\3\0\1\41\4\0\1\41\14\0\4\41\1\0"+
    "\2\41\1\244\1\0\17\41\40\0\1\245\65\0\1\246"+
    "\32\0\1\41\2\0\1\41\3\0\1\41\4\0\1\41"+
    "\14\0\2\41\1\247\1\41\1\0\3\41\1\0\17\41"+
    "\5\0\1\41\2\0\1\41\3\0\1\41\4\0\1\41"+
    "\14\0\2\41\1\250\1\41\1\0\3\41\1\0\17\41"+
    "\5\0\1\41\2\0\1\41\3\0\1\41\4\0\1\41"+
    "\14\0\4\41\1\0\3\41\1\0\4\41\1\251\12\41"+
    "\40\0\1\252\32\0\1\41\2\0\1\41\3\0\1\41"+
    "\4\0\1\41\14\0\2\41\1\253\1\41\1\0\3\41"+
    "\1\0\17\41\46\0\2\254\64\0\2\255\23\0\1\41"+
    "\2\0\1\41\3\0\1\41\4\0\1\41\14\0\4\41"+
    "\1\0\3\41\1\254\1\256\16\41\5\0\1\41\2\0"+
    "\1\41\3\0\1\41\4\0\1\41\14\0\4\41\1\0"+
    "\3\41\1\255\1\257\16\41\5\0\1\41\2\0\1\41"+
    "\3\0\1\41\4\0\1\41\14\0\1\41\1\260\2\41"+
    "\1\0\3\41\1\0\17\41\52\0\1\261\20\0\1\41"+
    "\2\0\1\41\3\0\1\41\4\0\1\41\14\0\4\41"+
    "\1\0\3\41\1\0\3\41\1\262\13\41\5\0\1\41"+
    "\2\0\1\41\3\0\1\41\4\0\1\41\14\0\4\41"+
    "\1\0\3\41\1\0\1\41\1\263\15\41\54\0\1\264"+
    "\16\0\1\41\2\0\1\41\3\0\1\41\4\0\1\41"+
    "\14\0\4\41\1\0\3\41\1\0\5\41\1\265\11\41"+
    "\5\0\1\41\2\0\1\41\3\0\1\41\4\0\1\41"+
    "\14\0\4\41\1\0\3\41\1\0\5\41\1\266\11\41"+
    "\46\0\2\267\23\0\1\41\2\0\1\41\3\0\1\41"+
    "\4\0\1\41\14\0\4\41\1\0\3\41\1\267\1\270"+
    "\16\41\5\0\1\41\2\0\1\41\3\0\1\41\4\0"+
    "\1\41\14\0\4\41\1\0\3\41\1\0\5\41\1\271"+
    "\11\41\5\0\1\41\2\0\1\41\3\0\1\41\4\0"+
    "\1\41\14\0\4\41\1\0\3\41\1\272\1\273\16\41"+
    "\50\0\1\274\22\0\1\41\2\0\1\41\3\0\1\41"+
    "\4\0\1\41\14\0\4\41\1\0\3\41\1\0\1\41"+
    "\1\275\15\41\40\0\1\276\32\0\1\41\2\0\1\41"+
    "\3\0\1\41\4\0\1\41\14\0\2\41\1\277\1\41"+
    "\1\0\3\41\1\0\17\41\63\0\1\300\7\0\1\41"+
    "\2\0\1\41\3\0\1\41\4\0\1\41\14\0\4\41"+
    "\1\0\3\41\1\0\14\41\1\301\2\41\42\0\2\302"+
    "\27\0\1\41\2\0\1\41\3\0\1\41\4\0\1\41"+
    "\14\0\4\41\1\302\1\303\2\41\1\0\17\41\46\0"+
    "\2\304\23\0\1\41\2\0\1\41\3\0\1\41\4\0"+
    "\1\41\14\0\4\41\1\0\3\41\1\304\1\305\16\41"+
    "\50\0\1\306\22\0\1\41\2\0\1\41\3\0\1\41"+
    "\4\0\1\41\14\0\4\41\1\0\3\41\1\0\1\41"+
    "\1\307\15\41\42\0\2\310\27\0\1\41\2\0\1\41"+
    "\3\0\1\41\4\0\1\41\14\0\4\41\1\310\1\311"+
    "\2\41\1\0\17\41\44\0\1\312\26\0\1\41\2\0"+
    "\1\41\3\0\1\41\4\0\1\41\14\0\4\41\1\0"+
    "\1\41\1\313\1\41\1\0\17\41\53\0\1\314\17\0"+
    "\1\41\2\0\1\41\3\0\1\41\4\0\1\41\14\0"+
    "\4\41\1\0\3\41\1\0\4\41\1\315\12\41\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8640];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\1\1\1\11\2\1\14\11"+
    "\11\1\1\0\1\1\3\0\5\1\1\0\1\1\1\0"+
    "\6\1\1\11\11\1\1\0\1\1\1\0\10\1\1\11"+
    "\5\1\1\0\1\1\1\0\4\1\1\0\1\1\1\11"+
    "\1\1\1\0\2\1\1\0\2\1\1\0\1\1\1\0"+
    "\3\1\1\0\1\1\1\0\2\1\1\0\2\1\1\11"+
    "\5\1\1\0\1\1\1\0\2\1\1\11\2\1\2\11"+
    "\2\1\1\11\1\1\1\0\1\1\3\0\4\1\1\0"+
    "\1\1\3\0\4\1\1\0\1\1\2\0\1\11\4\1"+
    "\1\0\1\1\2\0\3\1\1\0\1\1\2\0\3\1"+
    "\1\0\1\1\2\11\3\1\1\0\2\1\1\0\2\1"+
    "\1\11\2\1\1\0\1\1\1\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[205];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    //----> Codigo de usuario en sintaxis java


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ALexico(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(SimbolosJS.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Error Lexico"+yytext()+" Linea "+yyline+" Columna "+yycolumn);
            }
          case 39: break;
          case 2: 
            { System.out.println("Reconocio "+yytext()+" numero"); return new Symbol(SimbolosJS.numero, yycolumn, yyline, yytext());
            }
          case 40: break;
          case 3: 
            { System.out.println("Reconocio "+yytext()+" letra"); return new Symbol(SimbolosJS.letra, yycolumn, yyline, yytext());
            }
          case 41: break;
          case 4: 
            { System.out.println("Reconocio "+yytext()+" comilladoble"); return new Symbol(SimbolosJS.comilladoble, yycolumn, yyline, yytext());
            }
          case 42: break;
          case 5: 
            { /* Espacios en blanco, se ignoran */
            }
          case 43: break;
          case 6: 
            { System.out.println("Reconocio "+yytext()+" comillasimple"); return new Symbol(SimbolosJS.comillasimple, yycolumn, yyline, yytext());
            }
          case 44: break;
          case 7: 
            { System.out.println("Reconocio "+yytext()+" guionBajo"); return new Symbol(SimbolosJS.guionBajo, yycolumn, yyline, yytext());
            }
          case 45: break;
          case 8: 
            { System.out.println("Reconocio "+yytext()+" llaveabre"); return new Symbol(SimbolosJS.llaveabre, yycolumn, yyline, yytext());
            }
          case 46: break;
          case 9: 
            { System.out.println("Reconocio "+yytext()+" llavecierra"); return new Symbol(SimbolosJS.llavecierra, yycolumn, yyline, yytext());
            }
          case 47: break;
          case 10: 
            { System.out.println("Reconocio "+yytext()+" dospuntos"); return new Symbol(SimbolosJS.dospuntos, yycolumn, yyline, yytext());
            }
          case 48: break;
          case 11: 
            { System.out.println("Reconocio "+yytext()+" puntoycoma"); return new Symbol(SimbolosJS.puntoycoma, yycolumn, yyline, yytext());
            }
          case 49: break;
          case 12: 
            { System.out.println("Reconocio "+yytext()+" coma"); return new Symbol(SimbolosJS.coma, yycolumn, yyline, yytext());
            }
          case 50: break;
          case 13: 
            { System.out.println("Reconocio "+yytext()+" dolar"); return new Symbol(SimbolosJS.dolar, yycolumn, yyline, yytext());
            }
          case 51: break;
          case 14: 
            { System.out.println("Reconocio "+yytext()+" guion"); return new Symbol(SimbolosJS.guion, yycolumn, yyline, yytext());
            }
          case 52: break;
          case 15: 
            { System.out.println("Reconocio "+yytext()+" corcheteA"); return new Symbol(SimbolosJS.corcheteA, yycolumn, yyline, yytext());
            }
          case 53: break;
          case 16: 
            { System.out.println("Reconocio "+yytext()+" corcheteC"); return new Symbol(SimbolosJS.corcheteC, yycolumn, yyline, yytext());
            }
          case 54: break;
          case 17: 
            { System.out.println("Reconocio "+yytext()+" igual"); return new Symbol(SimbolosJS.igual, yycolumn, yyline, yytext());
            }
          case 55: break;
          case 18: 
            { System.out.println("Reconocio "+yytext()+" parentesisA"); return new Symbol(SimbolosJS.parentesisA, yycolumn, yyline, yytext());
            }
          case 56: break;
          case 19: 
            { System.out.println("Reconocio "+yytext()+" parentesisC"); return new Symbol(SimbolosJS.parentesisC, yycolumn, yyline, yytext());
            }
          case 57: break;
          case 20: 
            { System.out.println("Reconocio "+yytext()+" id"); return new Symbol(SimbolosJS.id, yycolumn, yyline, yytext());
            }
          case 58: break;
          case 21: 
            { System.out.println("Comentario: "+yytext());
            }
          case 59: break;
          case 22: 
            { System.out.println("Reconocio "+yytext()+" decimal"); return new Symbol(SimbolosJS.decimal, yycolumn, yyline, yytext());
            }
          case 60: break;
          case 23: 
            { System.out.println("Reconocio "+yytext()+" cadena"); return new Symbol(SimbolosJS.cadena, yycolumn, yyline, yytext());
            }
          case 61: break;
          case 24: 
            { System.out.println("Comentario doble: "+yytext());
            }
          case 62: break;
          case 25: 
            { System.out.println("Reconocio "+yytext()+" ejeX"); return new Symbol(SimbolosJS.ejeX, yycolumn, yyline, yytext());
            }
          case 63: break;
          case 26: 
            { System.out.println("Reconocio "+yytext()+" string"); return new Symbol(SimbolosJS.string, yycolumn, yyline, yytext());
            }
          case 64: break;
          case 27: 
            { System.out.println("Reconocio "+yytext()+" titulo"); return new Symbol(SimbolosJS.titulo, yycolumn, yyline, yytext());
            }
          case 65: break;
          case 28: 
            { System.out.println("Reconocio "+yytext()+" dou"); return new Symbol(SimbolosJS.dou, yycolumn, yyline, yytext());
            }
          case 66: break;
          case 29: 
            { System.out.println("Reconocio "+yytext()+" ar"); return new Symbol(SimbolosJS.ar, yycolumn, yyline, yytext());
            }
          case 67: break;
          case 30: 
            { System.out.println("Reconocio "+yytext()+" compare"); return new Symbol(SimbolosJS.compare, yycolumn, yyline, yytext());
            }
          case 68: break;
          case 31: 
            { System.out.println("Reconocio "+yytext()+" tituloX"); return new Symbol(SimbolosJS.tituloX, yycolumn, yyline, yytext());
            }
          case 69: break;
          case 32: 
            { System.out.println("Reconocio "+yytext()+" tituloY"); return new Symbol(SimbolosJS.tituloY, yycolumn, yyline, yytext());
            }
          case 70: break;
          case 33: 
            { System.out.println("Reconocio "+yytext()+" Valores"); return new Symbol(SimbolosJS.Valores, yycolumn, yyline, yytext());
            }
          case 71: break;
          case 34: 
            { System.out.println("Reconocio "+yytext()+" graficaPie"); return new Symbol(SimbolosJS.graficaPie, yycolumn, yyline, yytext());
            }
          case 72: break;
          case 35: 
            { System.out.println("Reconocio "+yytext()+" graficaBarras"); return new Symbol(SimbolosJS.graficaBarras, yycolumn, yyline, yytext());
            }
          case 73: break;
          case 36: 
            { System.out.println("Reconocio "+yytext()+" graficaLineas"); return new Symbol(SimbolosJS.graficaLineas, yycolumn, yyline, yytext());
            }
          case 74: break;
          case 37: 
            { System.out.println("Reconocio "+yytext()+" DefinirGlobales"); return new Symbol(SimbolosJS.DefinirGlobales, yycolumn, yyline, yytext());
            }
          case 75: break;
          case 38: 
            { System.out.println("Reconocio "+yytext()+" generarReporteEstadistico"); return new Symbol(SimbolosJS.generarReporteEstadistico, yycolumn, yyline, yytext());
            }
          case 76: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
