
/*--------------- 1ra Area: Codigo de Usuario -----------------------*/
//-------> importaciones, paquetes
package AnalizadoresJS;
import java_cup.runtime.Symbol;

import com.mycompany.proyecto1_2021s2.Ventana;
import com.mycompany.proyecto1_2021s2.errorJS;

import javax.swing.JOptionPane;
import java.util.LinkedList;
//------> Codigo para el parser,variables, metodos
parser code{:

        public void syntax_error(Symbol s)
        {
            System.err.println("Error en la Linea " + (s.right+1) +" Columna "+(s.left+1)+ ". Identificador "+s.value + " no reconocido. Se ha recuperado del error." );
            errorJS nuevo = new errorJS("Error Sintactico (Recuperado)", s.value.toString(), s.right+1, s.left+1);
            Ventana.listaErrores2.add(nuevo);
        }
        public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
        {
            System.err.println("Error en la Linea " + (s.right+1)+ " Columna "+(s.left+1)+". Identificador " +s.value + " no reconocido.");
            errorJS nuevo = new errorJS("Error Sintactico", s.value.toString(), s.right+1, s.left+1);
            Ventana.listaErrores2.add(nuevo);
        }

 :}


//------> Codigo para las acciones gramaticales
action code
{:  :}

/*--------------- 2da Area: Declaraciones -----------------------*/

//------> declaracion de terminales 

terminal String llaveabre,llavecierra;
terminal String dospuntos,puntoycoma,coma;
terminal String comilladoble, comillasimple;
terminal String numero,cadena,id,decimal,caracter, guion;
terminal String parentesisC, parentesisA,igual,unario;

terminal String punto,menorque,mayorque;


terminal String mas,menos,multiplicacion,division,modulo;


terminal String class_js,Class_js,require,true_js,false_js,if_js,else_js;
terminal String for_js,while_js,do_js,switch_js,case_js,break_js,default_js;
terminal String console_js, log_js;

terminal String var_js,let_js,const_js;

terminal especial;

//------> declaracion de no terminales

non terminal INICIO;
non terminal CLASES,CLASE;
non terminal INSTRUCCION,INSTRUCCIONES;
non terminal IMPORT,METODO,DECLARACIONVARIABLES,ASIGNACIONVARIABLES;
non terminal SENTENCIAIF,SENTENCIAFOR,SENTENCIAWHILE,SENTENCIADOWHILE,SENTENCIASWITCH;
non terminal CONSOLA,BREAK,LLAMADA;
non terminal TIPO,EXPRESION,EXPRESS,PARAMETROS,INSTRUCCIONESMETODO,INSTRUCCIONMETODO;
non terminal DECLARACIONFOR,CONTADOR,INCREMENTO;
non terminal CASOS,LISTAPARAMETROS;

//------> precedencia de menor a mayor

precedence left menorque;
precedence left mayorque;
precedence left mas;
precedence left menos;
precedence left multiplicacion;
precedence left division;
precedence left modulo;
precedence right unario;








start with INICIO;

/*--------------- 3ra Area: Reglas Semanticas -----------------------*/

INICIO::= CLASES                                                                                {: :}
    ;
CLASES::= CLASES CLASE
    |CLASE
    ;
CLASES::= class_js id parentesisA parentesisC llaveabre INSTRUCCIONES llavecierra                      {: :}
    | class_js id llaveabre INSTRUCCIONES llavecierra
    |Class_js id parentesisA parentesisC llaveabre INSTRUCCIONES llavecierra
    |Class_js id llaveabre INSTRUCCIONES llavecierra
    ;


INSTRUCCIONES::=INSTRUCCIONES INSTRUCCION
    |INSTRUCCION
    ;


INSTRUCCION::=IMPORT
    |METODO
    |DECLARACIONVARIABLES
    |ASIGNACIONVARIABLES
    |SENTENCIAIF
    |SENTENCIAFOR   
    |SENTENCIAWHILE
    |SENTENCIADOWHILE
    |SENTENCIASWITCH
    |CONSOLA
    |BREAK
    |LLAMADA
    ;

IMPORT::= TIPO id igual require parentesisA cadena parentesisC puntoycoma
    | TIPO id igual require parentesisA cadena parentesisC
    ;

METODO::= id parentesisA PARAMETROS parentesisC llaveabre INSTRUCCIONESMETODO llavecierra
    | id parentesisA  parentesisC llaveabre INSTRUCCIONESMETODO llavecierra
    ;

PARAMETROS::= PARAMETROS coma id
    |id
    ;
INSTRUCCIONESMETODO::= INSTRUCCIONESMETODO INSTRUCCIONMETODO
    |INSTRUCCIONMETODO
    ;

INSTRUCCIONMETODO::= DECLARACIONVARIABLES
    |ASIGNACIONVARIABLES
    |SENTENCIAIF
    |SENTENCIAFOR   
    |SENTENCIAWHILE
    |SENTENCIADOWHILE
    |SENTENCIASWITCH
    |CONSOLA
    |BREAK
    |LLAMADA
    ;

DECLARACIONVARIABLES::= TIPO id igual EXPRESION puntoycoma
    |TIPO id igual EXPRESION
    |TIPO id puntoycoma
    |TIPO id igual EXPRESS puntoycoma
    |TIPO id igual EXPRESS
    |TIPO id 
    ;

EXPRESION::= EXPRESION especial EXPRESION 
    |EXPRESION especial EXPRESION
    |EXPRESION menorque EXPRESION
    |EXPRESION mayorque EXPRESION
    |EXPRESION especial EXPRESION
    |EXPRESION especial EXPRESION
    |EXPRESION especial EXPRESION
    |EXPRESION especial EXPRESION
    |not EXPRESION
    |EXPRESION mas EXPRESION
    |EXPRESION menos EXPRESION
    |EXPRESION multiplicacion EXPRESION
    |EXPRESION division EXPRESION
    |EXPRESION especial EXPRESION
    |EXPRESION modulo EXPRESION
    |menos EXPRESION %prec unario
    |true_js
    |false_js
    |cadena
    |numero
    |decimal
    |caracter
    ;

EXPRESS::= id especial id
    |id diferencia id
    |id menorque id
    |id mayorque id
    |id especial id
    |id especial id
    |id especial id
    |id especial id
    |not id
    |id mas id
    |id menos id
    |id multiplicacion id
    |id division id
    |id especial id
    |id modulo id
    |menos id %prec unario
    ;

ASIGNACIONVARIABLES::= id igual EXPRESION puntoycoma
    |id igual EXPRESION
    |id igual EXPRESS puntoycoma
    |id igual EXPRESS
    ;

SENTENCIAIF::= if_js parentesisA EXPRESION parentesisC llaveabre INSTRUCCIONESMETODO llavecierra
    | if_js parentesisA EXPRESION parentesisC llaveabre INSTRUCCIONESMETODO llavecierra else_js SENTENCIAIF
    | if_js parentesisA EXPRESION parentesisC llaveabre INSTRUCCIONESMETODO llavecierra else_js llaveabre INSTRUCCIONESMETODO llavecierra
    | if_js parentesisA EXPRESS parentesisC llaveabre INSTRUCCIONESMETODO llavecierra
    | if_js parentesisA EXPRESS parentesisC llaveabre INSTRUCCIONESMETODO llavecierra else_js SENTENCIAIF
    | if_js parentesisA EXPRESS parentesisC llaveabre INSTRUCCIONESMETODO llavecierra else_js llaveabre INSTRUCCIONESMETODO llavecierra
    ;

SENTENCIAFOR::= for_js parentesisA DECLARACIONFOR puntoycoma EXPRESION puntoycoma CONTADOR parentesisC llaveabre INSTRUCCIONESMETODO llavecierra
    |for_js parentesisA DECLARACIONFOR puntoycoma EXPRESS puntoycoma CONTADOR parentesisC llaveabre INSTRUCCIONESMETODO llavecierra
    ;

DECLARACIONFOR::= TIPO id igual EXPRESION
    | id igual EXPRESION
    |TIPO id igual EXPRESS
    |id igual EXPRESS
    ;

CONTADOR::= id INCREMENTO
    ;
INCREMENTO::= mas mas
    |menos menos
    |mas numero
    |menos numero
    ;

TIPO::= var_js
    |let_js
    |const_js
    ;

SENTENCIAWHILE::= while_js parentesisA EXPRESION parentesisC llaveabre INSTRUCCIONESMETODO llavecierra
    |while_js parentesisA EXPRESS parentesisC llaveabre INSTRUCCIONESMETODO llavecierra
    ;

SENTENCIADOWHILE::= do_js llaveabre INSTRUCCIONESMETODO llavecierra while_js parentesisA EXPRESION parentesisC puntoycoma
    | do_js llaveabre INSTRUCCIONESMETODO llavecierra while_js parentesisA EXPRESION parentesisC
    |do_js llaveabre INSTRUCCIONESMETODO llavecierra while_js parentesisA EXPRESS parentesisC puntoycoma
    |do_js llaveabre INSTRUCCIONESMETODO llavecierra while_js parentesisA EXPRESS parentesisC
    ;

SENTENCIASWITCH::= switch_js parentesisA EXPRESION parentesisC llaveabre CASOS llavecierra
    |switch_js parentesisA EXPRESS parentesisC llaveabre CASOS llavecierra
    ;

CASOS::= case_js EXPRESION dospuntos INSTRUCCIONESMETODO
    |case_js EXPRESS dospuntos INSTRUCCIONESMETODO
    |default_js dospuntos INSTRUCCIONESMETODO
    ;

CONSOLA::=console_js punto log_js parentesisA EXPRESION parentesisC puntoycoma
    |console_js punto log_js parentesisA EXPRESS parentesisC puntoycoma
    ;

BREAK::= break_js puntoycoma
    | break_js
    ;

LLAMADA::= id parentesisA parentesisC puntoycoma
    |id parentesisA parentesisC
    |id parentesisA LISTAPARAMETROS parentesisC puntoycoma
    |id parentesisA LISTAPARAMETROS parentesisC 
    ;

LISTAPARAMETROS::= LISTAPARAMETROS coma EXPRESION
    |LISTAPARAMETROS coma EXPRESS
    |EXPRESION
    |EXPRESS
    ;