
/*--------------- 1ra Area: Codigo de Usuario -----------------------*/
//-------> importaciones, paquetes
package AnalizadoresJS;
import java_cup.runtime.Symbol;
import javax.swing.JOptionPane;

import com.mycompany.proyecto1_2021s2.Nodo;
import com.mycompany.proyecto1_2021s2.error;
import com.mycompany.proyecto1_2021s2.Ventana;
//------> Codigo para el parser,variables, metodos
parser code{:
        public String resultado = "";
        public static Nodo raiz; 
        
        public Nodo getRaiz(){
            return raiz;
        }

        public void syntax_error(Symbol s)
        {
            System.err.println("Error en la Linea " + (s.right+1) +" Columna "+(s.left+1)+ ". Identificador "+s.value + " no reconocido. Se ha recuperado del error." );
            error nuevo = new error("Error Sintactico (Recuperado)", s.value.toString(), s.right+1, s.left+1);
            Ventana.listaErrores.add(nuevo);
        }
        public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
        {
            System.err.println("Error en la Linea " + (s.right+1)+ " Columna "+(s.left+1)+". Identificador " +s.value + " no reconocido. No se Recupero");
            error nuevo = new error("Error Sintactico", s.value.toString(), s.right+1, s.left+1);
            Ventana.listaErrores.add(nuevo);
        }

 :}


//------> Codigo para las acciones gramaticales
action code
{:  :}

/*--------------- 2da Area: Declaraciones -----------------------*/

//------> declaracion de terminales 

terminal String llaveabre,llavecierra;
terminal String dospuntos,puntoycoma,coma;
terminal String comilladoble, comillasimple;
terminal String numero,cadena,id,decimal, guion;
terminal String parentesisC, parentesisA,igual,unario;

terminal String punto,menorque,mayorque;


terminal String mas,menos,multiplicacion,division,modulo;


terminal String class_js,Class_js,require,true_js,false_js,if_js,else_js;
terminal String for_js,while_js,do_js,switch_js,case_js,break_js,default_js;
terminal String console_js, log_js;

terminal String var_js,let_js,const_js;

terminal String and, or, not,menorIgual,mayorIgual,diferente,incremento,decremento,potencia,igualacion;

//------> declaracion de no terminales

non terminal Nodo INICIO;
non terminal Nodo CLASES,CLASE;
non terminal Nodo INSTRUCCION;
non terminal Nodo INSTRUCCIONES;
non terminal Nodo IMPORT,METODO,DECLARACIONVARIABLES,ASIGNACIONVARIABLES;
non terminal Nodo SENTENCIAIF,SENTENCIAFOR,SENTENCIAWHILE,SENTENCIADOWHILE,SENTENCIASWITCH;
non terminal Nodo CONSOLA,BREAK,LLAMADA;
non terminal Nodo TIPO;
non terminal Nodo PARAMETROS;
non terminal Nodo DECLARACIONFOR,CONTADOR;
non terminal Nodo CASOS,CASO;
non terminal Nodo EXPRESION;
//------> precedencia de menor a mayor

precedence left menorque, mayorque;
precedence left mas, menos;
precedence left multiplicacion, division;
precedence left modulo;
precedence right unario;

precedence left igualacion;
precedence left diferente;
precedence left menorIgual;
precedence left mayorIgual;
precedence left and;
precedence left or;
precedence left potencia;




start with INICIO;

/*--------------- 3ra Area: Reglas Semanticas -----------------------*/

INICIO::= CLASES:a                                                                                          {: parser.raiz = a;:}
    | error INICIO
    ;
CLASES::= CLASES:a CLASE:b                                                                                  {: Nodo padre = new Nodo("CLASES","",0,0);
                                                                                                               padre.AddHijo(a);
                                                                                                               padre.AddHijo(b);
                                                                                                               RESULT = padre;
                                                                                                            :}
    |CLASE:a                                                                                                {: Nodo padre = new Nodo("CLASES","",0,0);
                                                                                                               padre.AddHijo(a);
                                                                                                               RESULT = padre;
                                                                                                            :}
    ;
CLASE::= class_js:a id:b parentesisA:c parentesisC:d llaveabre:e INSTRUCCIONES:f llavecierra:g             {: Nodo padre = new Nodo("CLASE","",0,0);
                                                                                                              padre.AddHijo(new Nodo("class_js",a, aright, aleft));
                                                                                                              padre.AddHijo(new Nodo("id",b, bright, bleft));
                                                                                                              padre.AddHijo(new Nodo("parentesisA",c, cright, cleft));
                                                                                                              padre.AddHijo(new Nodo("parentesisC",d, dright, dleft));
                                                                                                              padre.AddHijo(new Nodo("llaveabre",e, eright, eleft));
                                                                                                              padre.AddHijo(f);
                                                                                                              padre.AddHijo(new Nodo("llavecierra",g, gright, gleft));
                                                                                                              RESULT = padre;
                                                                                                            :}
    | class_js:a id:b llaveabre:c INSTRUCCIONES:d llavecierra:e                                            {: Nodo padre = new Nodo("CLASE","",0,0);
                                                                                                              padre.AddHijo(new Nodo("class_js",a, aright, aleft));
                                                                                                              padre.AddHijo(new Nodo("id",b, bright, bleft));
                                                                                                              padre.AddHijo(new Nodo("llaveabre",c, cright, cleft));
                                                                                                              padre.AddHijo(d);
                                                                                                              padre.AddHijo(new Nodo("llavecierra",e, eright, eleft));
                                                                                                            :}
    | Class_js:a id:b parentesisA:c parentesisC:d llaveabre:e INSTRUCCIONES:f llavecierra:g                 {: Nodo padre = new Nodo("CLASE","",0,0);
                                                                                                              padre.AddHijo(new Nodo("Class_js",a, aright, aleft));
                                                                                                              padre.AddHijo(new Nodo("id",b, bright, bleft));
                                                                                                              padre.AddHijo(new Nodo("parentesisA",c, cright, cleft));
                                                                                                              padre.AddHijo(new Nodo("parentesisC",d, dright, dleft));
                                                                                                              padre.AddHijo(new Nodo("llaveabre",e, eright, eleft));
                                                                                                              padre.AddHijo(f);
                                                                                                              padre.AddHijo(new Nodo("llavecierra",g, gright, gleft));
                                                                                                              RESULT = padre;
                                                                                                            :}
    | Class_js:a id:b llaveabre:c INSTRUCCIONES:d llavecierra:e                                            {: Nodo padre = new Nodo("CLASE","",0,0);
                                                                                                              padre.AddHijo(new Nodo("Class_js",a, aright, aleft));
                                                                                                              padre.AddHijo(new Nodo("id",b, bright, bleft));
                                                                                                              padre.AddHijo(new Nodo("llaveabre",c, cright, cleft));
                                                                                                              padre.AddHijo(d);
                                                                                                              padre.AddHijo(new Nodo("llavecierra",e, eright, eleft));
                                                                                                            :}
    ;


INSTRUCCIONES::=INSTRUCCIONES:a INSTRUCCION:b                               {:  Nodo padre = new Nodo("INSTRUCCIONES","",0,0);
                                                                                padre.AddHijo(a);
                                                                                padre.AddHijo(b);
                                                                                RESULT = padre;
                                                                            :}
    |INSTRUCCION:a                                                          {:  Nodo padre = new Nodo("INSTRUCCIONES","",0,0);
                                                                                padre.AddHijo(a);
                                                                                RESULT = padre;
                                                                            :}
    ;


INSTRUCCION::=IMPORT:a                                                      {:  RESULT = a; :}
    |METODO:a                                                               {:  RESULT = a; :}
    |DECLARACIONVARIABLES:a                                                 {:  RESULT = a; :}
    |ASIGNACIONVARIABLES:a                                                  {:  RESULT = a; :}
    |SENTENCIAIF:a                                                          {:  RESULT = a; :}
    |SENTENCIAFOR:a                                                         {:  RESULT = a; :}
    |SENTENCIAWHILE:a                                                       {:  RESULT = a; :}
    |SENTENCIADOWHILE:a                                                     {:  RESULT = a; :}
    |SENTENCIASWITCH:a                                                      {:  RESULT = a; :}
    |CONSOLA:a                                                              {:  RESULT = a; :}
    |BREAK:a                                                                {:  RESULT = a; :}
    |LLAMADA:a                                                              {:  RESULT = a; :}
    |error
    ;

IMPORT::= TIPO:a id:b igual:c require:d parentesisA:e cadena:f parentesisC:g puntoycoma:h                   {: Nodo padre = new Nodo("IMPORT","",0,0);
                                                                                                               padre.AddHijo(a);
                                                                                                               padre.AddHijo(new Nodo("id",b, bright, bleft));
                                                                                                               padre.AddHijo(new Nodo("igual",c, cright, cleft));
                                                                                                               padre.AddHijo(new Nodo("require",d, dright, dleft));
                                                                                                               padre.AddHijo(new Nodo("parentesisA",e, eright, eleft));
                                                                                                               padre.AddHijo(new Nodo("cadena",f, fright, fleft));
                                                                                                               padre.AddHijo(new Nodo("parentesisC",g, gright, gleft));
                                                                                                               padre.AddHijo(new Nodo("puntoycoma",h, hright, hleft));
                                                                                                               RESULT = padre;
                                                                                                            :}
    | TIPO:a id:b igual:c require:d parentesisA:e cadena:f parentesisC:g                                    {: Nodo padre = new Nodo("IMPORT","",0,0);
                                                                                                               padre.AddHijo(a);
                                                                                                               padre.AddHijo(new Nodo("id",b, bright, bleft));
                                                                                                               padre.AddHijo(new Nodo("igual",c, cright, cleft));
                                                                                                               padre.AddHijo(new Nodo("require",d, dright, dleft));
                                                                                                               padre.AddHijo(new Nodo("parentesisA",e, eright, eleft));
                                                                                                               padre.AddHijo(new Nodo("cadena",f, fright, fleft));
                                                                                                               padre.AddHijo(new Nodo("parentesisC",g, gright, gleft));
                                                                                                               RESULT = padre;
                                                                                                            :}
    ;

METODO::= id:a parentesisA:b PARAMETROS:c parentesisC:d llaveabre:e INSTRUCCIONES:f llavecierra:g           {: Nodo padre = new Nodo("METODO","",0,0);
                                                                                                               padre.AddHijo(new Nodo("id",a, aright, aleft));
                                                                                                               padre.AddHijo(new Nodo("parentesisA",b, bright, bleft));
                                                                                                               padre.AddHijo(c);
                                                                                                               padre.AddHijo(new Nodo("parentesisC",d, dright, dleft));
                                                                                                               padre.AddHijo(new Nodo("llaveabre",e, eright, eleft));
                                                                                                               padre.AddHijo(f);
                                                                                                               padre.AddHijo(new Nodo("llavecierra",g, gright, gleft));
                                                                                                               RESULT = padre;
                                                                                                            :}
    | id:a parentesisA:b  parentesisC:c llaveabre:d INSTRUCCIONES:e llavecierra:f                           {: Nodo padre = new Nodo("METODO","",0,0);
                                                                                                               padre.AddHijo(new Nodo("id",a, aright, aleft));
                                                                                                               padre.AddHijo(new Nodo("parentesisA",b, bright, bleft));
                                                                                                               padre.AddHijo(new Nodo("parentesisC",c, cright, cleft));
                                                                                                               padre.AddHijo(new Nodo("llaveabre",d, dright, dleft));
                                                                                                               padre.AddHijo(e);
                                                                                                               padre.AddHijo(new Nodo("llavecierra",f, fright, fleft));
                                                                                                               RESULT = padre;
                                                                                                            :}
    ;

PARAMETROS::= PARAMETROS:a coma:b EXPRESION:c                               {:  Nodo padre = new Nodo("PARAMETROS","",0,0);
                                                                                padre.AddHijo(a);
                                                                                padre.AddHijo(new Nodo("coma",b, bright, bleft));
                                                                                padre.AddHijo(c);
                                                                                RESULT = padre;
                                                                            :}
    |EXPRESION:a                                                            {:  Nodo padre = new Nodo("PARAMETROS","",0,0);
                                                                                padre.AddHijo(a);
                                                                                RESULT = padre;
                                                                            :}
    ;


DECLARACIONVARIABLES::= TIPO:a id:b igual:c EXPRESION:d puntoycoma:e        {:  Nodo padre = new Nodo("DECLARACIONVARIABLES","",0,0);
                                                                                padre.AddHijo(a);
                                                                                padre.AddHijo(new Nodo("id",b, bright, bleft));
                                                                                padre.AddHijo(new Nodo("igual",c, cright, cleft));
                                                                                padre.AddHijo(d);
                                                                                padre.AddHijo(new Nodo("puntoycoma",e, eright, eleft));
                                                                                RESULT = padre;
                                                                            :}
    |TIPO:a id:b igual:c EXPRESION:d                                        {:  Nodo padre = new Nodo("DECLARACIONVARIABLES","",0,0);
                                                                                padre.AddHijo(a);
                                                                                padre.AddHijo(new Nodo("id",b, bright, bleft));
                                                                                padre.AddHijo(new Nodo("igual",c, cright, cleft));
                                                                                padre.AddHijo(d);
                                                                                RESULT = padre;
                                                                            :}
    |TIPO:a id:b puntoycoma:c                                               {:  Nodo padre = new Nodo("DECLARACIONVARIABLES","",0,0);
                                                                                padre.AddHijo(a);
                                                                                padre.AddHijo(new Nodo("id",b, bright, bleft));
                                                                                padre.AddHijo(new Nodo("puntoycoma",c, cright, cleft));
                                                                                RESULT = padre;
                                                                            :}
    |CONTADOR:a puntoycoma:b                                                {:  Nodo padre = new Nodo("DECLARACIONVARIABLES","",0,0);
                                                                                padre.AddHijo(a);
                                                                                padre.AddHijo(new Nodo("puntoycoma",b, bright, bleft));
                                                                                RESULT = padre;
                                                                            :}
    |CONTADOR:a                                                             {:  Nodo padre = new Nodo("DECLARACIONVARIABLES","",0,0);
                                                                                padre.AddHijo(a);
                                                                                RESULT = padre;
                                                                            :} 
    |TIPO:a id:b                                                            {:  Nodo padre = new Nodo("DECLARACIONVARIABLES","",0,0);
                                                                                padre.AddHijo(a);
                                                                                padre.AddHijo(new Nodo("id",b, bright, bleft));
                                                                                RESULT = padre;
                                                                            :} 
    ;

    EXPRESION::= EXPRESION:a igualacion:b EXPRESION:c                       {:  Nodo padre = new Nodo("EXPRESION", "", 0,0); 
                                                                                padre.AddHijo(a);
                                                                                padre.AddHijo(new Nodo("igualacion", b, bright, bleft));
                                                                                padre.AddHijo(c);
                                                                                RESULT = padre;
                                                                            :} 
        |EXPRESION:a diferente:b EXPRESION:c                                {:  Nodo padre = new Nodo("EXPRESION", "", 0,0); 
                                                                                padre.AddHijo(a);
                                                                                padre.AddHijo(new Nodo("diferente", b, bright, bleft));
                                                                                padre.AddHijo(c);
                                                                                RESULT = padre;                                         
                                                                            :}
        |EXPRESION:a menorque:b EXPRESION:c                                 {:  Nodo padre = new Nodo("EXPRESION", "", 0,0); 
                                                                                padre.AddHijo(a);
                                                                                padre.AddHijo(new Nodo("menorque", b, bright, bleft));
                                                                                padre.AddHijo(c);
                                                                                RESULT = padre;                                         
                                                                            :}
        |EXPRESION:a mayorque:b EXPRESION:c                                 {:  Nodo padre = new Nodo("EXPRESION", "", 0,0); 
                                                                                padre.AddHijo(a);
                                                                                padre.AddHijo(new Nodo("mayorque", b, bright, bleft));
                                                                                padre.AddHijo(c);
                                                                                RESULT = padre;                                           
                                                                            :}
        |EXPRESION:a menorIgual:b EXPRESION:c                               {:  Nodo padre = new Nodo("EXPRESION", "", 0,0); 
                                                                                padre.AddHijo(a);
                                                                                padre.AddHijo(new Nodo("menorIgual", b, bright, bleft));
                                                                                padre.AddHijo(c);
                                                                                RESULT = padre;
                                                                            :}
        |EXPRESION:a mayorIgual:b EXPRESION:c                               {:  Nodo padre = new Nodo("EXPRESION", "", 0,0); 
                                                                                padre.AddHijo(a);
                                                                                padre.AddHijo(new Nodo("mayorIgual", b, bright, bleft));
                                                                                padre.AddHijo(c);
                                                                                RESULT = padre;
                                                                            :}
        |EXPRESION:a and:b EXPRESION:c                                      {:  Nodo padre = new Nodo("EXPRESION", "", 0,0); 
                                                                                padre.AddHijo(a);
                                                                                padre.AddHijo(new Nodo("and", b, bright, bleft));
                                                                                padre.AddHijo(c);
                                                                                RESULT = padre;
                                                                            :}
        |EXPRESION:a or:b EXPRESION:c                                       {:  Nodo padre = new Nodo("EXPRESION", "", 0,0); 
                                                                                padre.AddHijo(a);
                                                                                padre.AddHijo(new Nodo("or", b, bright, bleft));
                                                                                padre.AddHijo(c);
                                                                                RESULT = padre;
                                                                            :}
        |not:a EXPRESION:b                                                  {:  Nodo padre = new Nodo("EXPRESION", "", 0,0); 
                                                                                padre.AddHijo(new Nodo("not", a, bright, bleft));
                                                                                padre.AddHijo(b);
                                                                                RESULT = padre;
                                                                            :}
        |EXPRESION:a mas:b EXPRESION:c                                      {:  Nodo padre = new Nodo("EXPRESION", "", 0, 0);
                                                                                padre.AddHijo(a);
                                                                                Nodo hijo1 = new Nodo("mas", b, bright, bleft);
                                                                                padre.AddHijo(hijo1);
                                                                                padre.AddHijo(c);
                                                                                RESULT = padre;
                                                                            :}
        |EXPRESION:a menos:b EXPRESION:c                                    {:  Nodo padre = new Nodo("EXPRESION", "", 0, 0);
                                                                                padre.AddHijo(a);
                                                                                Nodo hijo1 = new Nodo("menos", b, bright, bleft);
                                                                                padre.AddHijo(hijo1);
                                                                                padre.AddHijo(c);
                                                                                RESULT = padre;
                                                                            :}
        |EXPRESION:a multiplicacion:b EXPRESION:c                           {:  Nodo padre = new Nodo("EXPRESION", "", 0, 0);
                                                                                padre.AddHijo(a);
                                                                                Nodo hijo1 = new Nodo("multiplicacion", b, bright, bleft);
                                                                                padre.AddHijo(hijo1);
                                                                                padre.AddHijo(c);
                                                                                RESULT = padre;
                                                                            :}
        |EXPRESION:a division:b EXPRESION:c                                 {:  Nodo padre = new Nodo("EXPRESION", "", 0, 0);
                                                                                padre.AddHijo(a);
                                                                                Nodo hijo1 = new Nodo("division", b, bright, bleft);
                                                                                padre.AddHijo(hijo1);
                                                                                padre.AddHijo(c);
                                                                                RESULT = padre;
                                                                            :}
        |EXPRESION:a potencia:b EXPRESION:c                                 {:  Nodo padre = new Nodo("EXPRESION", "", 0, 0);
                                                                                padre.AddHijo(a);
                                                                                Nodo hijo1 = new Nodo("potencia", b, bright, bleft);
                                                                                padre.AddHijo(hijo1);
                                                                                padre.AddHijo(c);
                                                                                RESULT = padre;
                                                                            :}
        |EXPRESION:a modulo:b EXPRESION:c                                   {:  Nodo padre = new Nodo("EXPRESION", "", 0, 0);
                                                                                padre.AddHijo(a);
                                                                                Nodo hijo1 = new Nodo("modulo", b, bright, bleft);
                                                                                padre.AddHijo(hijo1);
                                                                                padre.AddHijo(c);
                                                                                RESULT = padre;
                                                                            :}
        |menos:a EXPRESION:b                                                {:  Nodo padre = new Nodo("EXPRESION", "", 0,0); 
                                                                                padre.AddHijo(new Nodo("menos", a, aright, aleft));
                                                                                padre.AddHijo(b);
                                                                                RESULT = padre;                                         
                                                                            :} %prec unario
        |true_js:a                                                          {:  Nodo padre = new Nodo("EXPRESION", "", 0, 0);
                                                                                Nodo hijo = new Nodo("true_js", a, aright, aleft);
                                                                                padre.AddHijo(hijo);
                                                                                RESULT = padre;            
                                                                            :}
        |false_js:a                                                         {:  Nodo padre = new Nodo("EXPRESION", "", 0, 0);
                                                                                Nodo hijo = new Nodo("false_js", a, aright, aleft);
                                                                                padre.AddHijo(hijo);
                                                                                RESULT = padre;            
                                                                            :}
        |cadena:a                                                           {:  Nodo padre = new Nodo("EXPRESION", "", 0, 0);
                                                                                Nodo hijo = new Nodo("cadena", a, aright, aleft);
                                                                                padre.AddHijo(hijo);
                                                                                RESULT = padre;            
                                                                            :}
        |numero:a                                                           {:  Nodo padre = new Nodo("EXPRESION", "", 0, 0);
                                                                                Nodo hijo = new Nodo("numero", a, aright, aleft);
                                                                                padre.AddHijo(hijo);
                                                                                RESULT = padre;            
                                                                            :}
        |decimal:a                                                          {:  Nodo padre = new Nodo("EXPRESION", "", 0, 0);
                                                                                Nodo hijo = new Nodo("id", a, aright, aleft);
                                                                                padre.AddHijo(hijo);
                                                                                RESULT = padre;            
                                                                            :}
        |id:a                                                               {:  Nodo padre = new Nodo("EXPRESION", "", 0, 0);
                                                                                Nodo hijo = new Nodo("id", a, aright, aleft);
                                                                                padre.AddHijo(hijo);
                                                                                RESULT = padre;            
                                                                            :}
    ;


ASIGNACIONVARIABLES::= id:a igual:b EXPRESION:c puntoycoma:d                {:  Nodo padre= new Nodo("ASIGNACIONVARIABLES","",0,0);
                                                                                padre.AddHijo(new Nodo("id",a, aright, aleft));
                                                                                padre.AddHijo(new Nodo("igual",b, bright, bleft));
                                                                                padre.AddHijo(c);
                                                                                padre.AddHijo(new Nodo("puntoycoma",d, dright, dleft));
                                                                                RESULT = padre;
                                                                            :}
    |id:a igual:b EXPRESION:c                                               {:  Nodo padre= new Nodo("ASIGNACIONVARIABLES","",0,0);
                                                                                padre.AddHijo(new Nodo("id",a, aright, aleft));
                                                                                padre.AddHijo(new Nodo("igual",b, bright, bleft));
                                                                                padre.AddHijo(c);
                                                                                RESULT = padre;
                                                                            :}

    ;

SENTENCIAIF::= if_js:a parentesisA:b EXPRESION:c parentesisC:d llaveabre:e INSTRUCCIONES:f llavecierra:g  {: Nodo padre= new Nodo("SENTENCIAIF","",0,0);
                                                                                                             padre.AddHijo(new Nodo("if_js",a, aright, aleft));
                                                                                                             padre.AddHijo(new Nodo("parentesisA",b, bright, bleft));
                                                                                                             padre.AddHijo(c);
                                                                                                             padre.AddHijo(new Nodo("parentesisC",d, dright, dleft));
                                                                                                             padre.AddHijo(new Nodo("llaveabre",e, eright, eleft));
                                                                                                             padre.AddHijo(f);
                                                                                                             padre.AddHijo(new Nodo("llavecierra",g, gright, gleft));
                                                                                                             RESULT= padre;
                                                                                                          :}
    | if_js:a parentesisA:b EXPRESION:c parentesisC:d llaveabre:e INSTRUCCIONES:f llavecierra:g else_js:h SENTENCIAIF:i  {: Nodo padre= new Nodo("SENTENCIAIF","",0,0);
                                                                                                                            padre.AddHijo(new Nodo("if_js",a, aright, aleft));
                                                                                                                            padre.AddHijo(new Nodo("parentesisA",b, bright, bleft));
                                                                                                                            padre.AddHijo(c);
                                                                                                                            padre.AddHijo(new Nodo("parentesisC",d, dright, dleft));
                                                                                                                            padre.AddHijo(new Nodo("llaveabre",e, eright, eleft));
                                                                                                                            padre.AddHijo(f);
                                                                                                                            padre.AddHijo(new Nodo("llavecierra",g, gright, gleft));
                                                                                                                            padre.AddHijo(new Nodo("else_js",h, hright, hleft));
                                                                                                                            padre.AddHijo(i);
                                                                                                                            RESULT=padre;
                                                                                                                         :}
    | if_js:a parentesisA:b EXPRESION:c parentesisC:d llaveabre:e INSTRUCCIONES:f llavecierra:g else_js:h llaveabre:i INSTRUCCIONES:j llavecierra:k  {: Nodo padre= new Nodo("SENTENCIAIF","",0,0);
                                                                                                                                                        padre.AddHijo(new Nodo("if_js",a, aright, aleft));
                                                                                                                                                        padre.AddHijo(new Nodo("parentesisA",b, bright, bleft));
                                                                                                                                                        padre.AddHijo(c);
                                                                                                                                                        padre.AddHijo(new Nodo("parentesisC",d, dright, dleft));
                                                                                                                                                        padre.AddHijo(new Nodo("llaveabre",e, eright, eleft));
                                                                                                                                                        padre.AddHijo(f);
                                                                                                                                                        padre.AddHijo(new Nodo("llavecierra",g, gright, gleft));
                                                                                                                                                        padre.AddHijo(new Nodo("else_js",h, hright, hleft));
                                                                                                                                                        padre.AddHijo(new Nodo("llaveabre",i, iright, ileft));
                                                                                                                                                        padre.AddHijo(j);
                                                                                                                                                        padre.AddHijo(new Nodo("llavecierra",k, kright, kleft));
                                                                                                                                                        RESULT=padre;
                                                                                                                                                     :}
    ;

SENTENCIAFOR::= for_js:a parentesisA:b DECLARACIONFOR:c puntoycoma:d EXPRESION:e puntoycoma:f CONTADOR:g parentesisC:h llaveabre:i INSTRUCCIONES:j llavecierra:k  {: Nodo padre= new Nodo("SENTENCIAFOR","",0,0);
                                                                                                                                                                  padre.AddHijo(new Nodo("for_js",a,aright, aleft));
                                                                                                                                                                  padre.AddHijo(new Nodo ("parentesisA",b,bright, bleft));
                                                                                                                                                                  padre.AddHijo(c);
                                                                                                                                                                  padre.AddHijo(new Nodo ("puntoycoma",d,dright, dleft));
                                                                                                                                                                  padre.AddHijo(e);
                                                                                                                                                                  padre.AddHijo(new Nodo("puntoycoma",f, fright, fleft));
                                                                                                                                                                  padre.AddHijo(g);
                                                                                                                                                                  padre.AddHijo(new Nodo("parentesisC",h, hright, hleft));
                                                                                                                                                                  padre.AddHijo(new Nodo ("llaveabre",i, iright, ileft));
                                                                                                                                                                  padre.AddHijo(j);
                                                                                                                                                                  padre.AddHijo(new Nodo ("llavecierra",k, kright, kleft));
                                                                                                                                                                  RESULT = padre;
                                                                                                                                                                    :}
    ;

DECLARACIONFOR::= TIPO:a id:b igual:c EXPRESION:d                           {:  Nodo padre = new Nodo ("DECLARACIONFOR","",0,0);
                                                                                padre.AddHijo(a);
                                                                                padre.AddHijo(new Nodo ("id", b, bright, bleft));
                                                                                padre.AddHijo(new Nodo ("igual", c, cright, cleft));
                                                                                padre.AddHijo(d);
                                                                                RESULT = padre;
                                                                            :}
    | id:a igual:b EXPRESION:c                                              {:  Nodo padre = new Nodo ("DECLARACIONFOR","",0,0);
                                                                                padre.AddHijo(new Nodo ("id",a, aright, aleft));
                                                                                padre.AddHijo(new Nodo ("igual",b, bright, bleft));
                                                                                padre.AddHijo(c);
                                                                                RESULT = padre;
                                                                            :}
    ;

CONTADOR::= id:a incremento:b                                               {:  Nodo padre = new Nodo ("CONTADOR","",0,0);
                                                                                padre.AddHijo(new Nodo("id", a, aright, aleft));
                                                                                padre.AddHijo(new Nodo("incremento", b, bright, bleft));
                                                                                RESULT = padre;
                                                                            :}
    | id:a decremento:b                                                     {:  Nodo padre = new Nodo ("CONTADOR","",0,0);
                                                                                padre.AddHijo(new Nodo("id", a, aright, aleft));
                                                                                padre.AddHijo(new Nodo("decremento", b, bright, bleft));
                                                                                RESULT = padre;
                                                                            :}
    ;

TIPO::= var_js:a                                                            {:  Nodo padre = new Nodo("TIPO","",0,0);
                                                                                Nodo hijo= new Nodo("var", a, aright, aleft); 
                                                                                padre.AddHijo(hijo);
                                                                                RESULT = padre;
                                                                            :}
    |let_js:a                                                               {:  Nodo padre = new Nodo("TIPO","",0,0);
                                                                                Nodo hijo= new Nodo("let", a, aright, aleft); 
                                                                                padre.AddHijo(hijo);
                                                                                RESULT = padre;
                                                                            :}
    |const_js:a                                                             {:  Nodo padre = new Nodo("TIPO","",0,0);
                                                                                Nodo hijo= new Nodo("const", a, aright, aleft); 
                                                                                padre.AddHijo(hijo);
                                                                                RESULT = padre;
                                                                            :}

    ;


SENTENCIAWHILE::= while_js:a parentesisA:b EXPRESION:c parentesisC:d llaveabre:e INSTRUCCIONES:f llavecierra:g  {: Nodo padre= new Nodo("SENTENCIAWHILE","",0,0);
                                                                                                                   padre.AddHijo(new Nodo("while_js",a, aright, aleft));
                                                                                                                   padre.AddHijo(new Nodo("parentesisA",b, bright, bleft));
                                                                                                                   padre.AddHijo(c);
                                                                                                                   padre.AddHijo(new Nodo("parentesisC",d, dright, dleft));
                                                                                                                   padre.AddHijo(new Nodo("llaveabre",e, eright, eleft));
                                                                                                                   padre.AddHijo(f);
                                                                                                                   padre.AddHijo(new Nodo("llavecierra",g, gright, gleft));
                                                                                                                   RESULT = padre;
                                                                                                                :}
    ;

SENTENCIADOWHILE::= do_js:a llaveabre:b INSTRUCCIONES:c llavecierra:d while_js:e parentesisA:f EXPRESION:g parentesisC:h puntoycoma:i  {: Nodo padre= new Nodo("SENTENCIADOWHILE","",0,0);
                                                                                                                                          padre.AddHijo(new Nodo("do_js",a, aright, aleft));
                                                                                                                                          padre.AddHijo(new Nodo("llaveabre",b, bright, bleft));
                                                                                                                                          padre.AddHijo(c);
                                                                                                                                          padre.AddHijo(new Nodo("llavecierra",d, dright, dleft));
                                                                                                                                          padre.AddHijo(new Nodo("while_js",e, eright, eleft));
                                                                                                                                          padre.AddHijo(new Nodo("parentesisA",f, fright, fleft));
                                                                                                                                          padre.AddHijo(g);
                                                                                                                                          padre.AddHijo(new Nodo("parentesisC",h, hright, hleft));
                                                                                                                                          padre.AddHijo(new Nodo("puntoycoma",i, iright, ileft));
                                                                                                                                          RESULT = padre;
                                                                                                                                        :}
    | do_js:a llaveabre:b INSTRUCCIONES:c llavecierra:d while_js:e parentesisA:f EXPRESION:g parentesisC:h  {: Nodo padre= new Nodo("SENTENCIADOWHILE","",0,0);
                                                                                                               padre.AddHijo(new Nodo("do_js",a, aright, aleft));
                                                                                                               padre.AddHijo(new Nodo("llaveabre",b, bright, bleft));
                                                                                                               padre.AddHijo(c);
                                                                                                               padre.AddHijo(new Nodo("llavecierra",d, dright, dleft));
                                                                                                               padre.AddHijo(new Nodo("while_js",e, eright, eleft));
                                                                                                               padre.AddHijo(new Nodo("parentesisA",f, fright, fleft));
                                                                                                               padre.AddHijo(g);
                                                                                                               padre.AddHijo(new Nodo("parentesisC",h, hright, hleft));
                                                                                                               RESULT = padre;
                                                                                                            :}
    ;

SENTENCIASWITCH::= switch_js:a parentesisA:b EXPRESION:c parentesisC:d llaveabre:e CASOS:f llavecierra:g  {: Nodo padre= new Nodo("SENTENCIASWITCH","",0,0);
                                                                                                             padre.AddHijo(new Nodo("switch_js",a, aright, aleft));
                                                                                                             padre.AddHijo(new Nodo("parentesisA",b, bright, bleft));
                                                                                                             padre.AddHijo(c);
                                                                                                             padre.AddHijo(new Nodo("parentesisC",d, dright, dleft));
                                                                                                             padre.AddHijo(new Nodo("llaveabre",e, eright, eleft));
                                                                                                             padre.AddHijo(f);
                                                                                                             padre.AddHijo(new Nodo("llavecierra",g, gright, gleft));
                                                                                                             RESULT = padre;
                                                                                                          :}
    ;

CASOS::= CASOS:a CASO:b                                                     {:  Nodo padre= new Nodo("CASOS","",0,0);
                                                                                padre.AddHijo(a);
                                                                                padre.AddHijo(b);
                                                                                RESULT = padre;
                                                                            :}
    |CASO:a                                                                 {:  Nodo padre= new Nodo("CASOS","",0,0);
                                                                                padre.AddHijo(a);
                                                                                RESULT = padre;
                                                                            :}
    ;

CASO::= case_js:a EXPRESION:b dospuntos:c INSTRUCCIONES:d                   {:  Nodo padre= new Nodo("CASO","",0,0);
                                                                                padre.AddHijo(new Nodo("case_js",a, aright, aleft));
                                                                                padre.AddHijo(b);
                                                                                padre.AddHijo(new Nodo("dospuntos",c, cright, cleft));
                                                                                padre.AddHijo(d);
                                                                                RESULT = padre;
                                                                            :}
    |default_js:a dospuntos:b INSTRUCCIONES:c                               {:  Nodo padre= new Nodo("CASO","",0,0);
                                                                                padre.AddHijo(new Nodo("default_js",a, aright, aleft));
                                                                                padre.AddHijo(new Nodo("dospuntos",b, bright, bleft));
                                                                                padre.AddHijo(c);
                                                                                RESULT = padre;
                                                                            :}
    ;

CONSOLA::=console_js:a punto:b log_js:c parentesisA:d EXPRESION:e parentesisC:f puntoycoma:g  {: Nodo padre= new Nodo("CONSOLA","",0,0);
                                                                                                 padre.AddHijo(new Nodo("console_js",a, aright, aleft));
                                                                                                 padre.AddHijo(new Nodo("punto",b, bright, bleft));
                                                                                                 padre.AddHijo(new Nodo("log_js",c, cright, cleft));
                                                                                                 padre.AddHijo(new Nodo("parentesisA",d, dright, dleft));
                                                                                                 padre.AddHijo(e);
                                                                                                 padre.AddHijo(new Nodo("parentesisC",f, fright, fleft));
                                                                                                 padre.AddHijo(new Nodo("puntoycoma",g, gright, gleft));
                                                                                                 RESULT = padre;
                                                                                              :}
    ;

BREAK::= break_js:a puntoycoma:b                                            {:  Nodo padre= new Nodo("BREAK","",0,0);
                                                                                padre.AddHijo(new Nodo("break_js",a, aright, aleft));
                                                                                padre.AddHijo(new Nodo("puntoycoma",b, bright, bleft));
                                                                                RESULT = padre;
                                                                            :}
    | break_js:a                                                            {:  Nodo padre= new Nodo("BREAK","",0,0);
                                                                                padre.AddHijo(new Nodo("break_js",a, aright, aleft));
                                                                                RESULT = padre;
                                                                            :}
    ;

LLAMADA::= id:a parentesisA:b parentesisC:c puntoycoma:d                    {:  Nodo padre= new Nodo("LLAMADA","",0,0);
                                                                                padre.AddHijo(new Nodo("id",a, aright, aleft));
                                                                                padre.AddHijo(new Nodo("parentesisA",b, bright, bleft));
                                                                                padre.AddHijo(new Nodo("parentesisC",c, cright, cleft));
                                                                                padre.AddHijo(new Nodo("puntoycoma",d, dright, dleft));
                                                                                RESULT = padre;
                                                                            :}
    |id:a parentesisA:b parentesisC:c                                       {:  Nodo padre= new Nodo("LLAMADA","",0,0);
                                                                                padre.AddHijo(new Nodo("id",a, aright, aleft));
                                                                                padre.AddHijo(new Nodo("parentesisA",b, bright, bleft));
                                                                                padre.AddHijo(new Nodo("parentesisC",c, cright, cleft));
                                                                                RESULT = padre;
                                                                            :}
    |id:a parentesisA:b PARAMETROS:c parentesisC:d puntoycoma:e             {:  Nodo padre= new Nodo("LLAMADA","",0,0);
                                                                                padre.AddHijo(new Nodo("id",a, aright, aleft));
                                                                                padre.AddHijo(new Nodo("parentesisA",b, bright, bleft));
                                                                                padre.AddHijo(c);
                                                                                padre.AddHijo(new Nodo("parentesisC",d, dright, dleft));
                                                                                padre.AddHijo(new Nodo("puntoycoma",e, eright, eleft));
                                                                                RESULT = padre;
                                                                            :}
    |id:a parentesisA:b PARAMETROS:c parentesisC:d                          {:  Nodo padre= new Nodo("LLAMADA","",0,0);
                                                                                padre.AddHijo(new Nodo("id",a, aright, aleft));
                                                                                padre.AddHijo(new Nodo("parentesisA",b, bright, bleft));
                                                                                padre.AddHijo(c);
                                                                                padre.AddHijo(new Nodo("parentesisC",d, dright, dleft));
                                                                                RESULT = padre;
                                                                            :} 
    ;
