
/*--------------- 1ra Area: Codigo de Usuario -----------------------*/
//-------> importaciones, paquetes
package AnalizadoresJS;
import java_cup.runtime.Symbol;

import com.mycompany.proyecto1_2021s2.Ventana;
import com.mycompany.proyecto1_2021s2.errorJS;

import javax.swing.JOptionPane;
import java.util.LinkedList;
//------> Codigo para el parser,variables, metodos
parser code{:

        public void syntax_error(Symbol s)
        {
            System.err.println("Error en la Linea " + (s.right+1) +" Columna "+(s.left+1)+ ". Identificador "+s.value + " no reconocido. Se ha recuperado del error." );
            errorJS nuevo = new errorJS("Error Sintactico (Recuperado)", s.value.toString(), s.right+1, s.left+1);
            Ventana.listaErrores2.add(nuevo);
        }
        public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
        {
            System.err.println("Error en la Linea " + (s.right+1)+ " Columna "+(s.left+1)+". Identificador " +s.value + " no reconocido.");
            errorJS nuevo = new errorJS("Error Sintactico", s.value.toString(), s.right+1, s.left+1);
            Ventana.listaErrores2.add(nuevo);
        }

 :}


//------> Codigo para las acciones gramaticales
action code
{:  :}

/*--------------- 2da Area: Declaraciones -----------------------*/

//------> declaracion de terminales 

terminal String llaveabre,llavecierra;
terminal String dospuntos,puntoycoma,coma;
terminal String comilladoble, comillasimple;
terminal String numero,cadena,id,decimal,caracter, guion;
terminal String parentesisC, parentesisA,igual;

terminal String punto,igualigual,diferente,menorque,mayorque;
terminal String menorIgual,mayorIgual,AND,OR,NOT;

terminal String mas,menos,multiplicacion,division,potencia,modulo;

terminal String incrementoUno,decrementoUno;

terminal String class_js,require,true_js,false_js,if_js,else_js;
terminal String for_js,while_js,do_js,switch_js,case_js,break_js;
terminal String console_js, log_js;

terminal String string_js,double_js,bool_js,int_js;


//------> declaracion de no terminales

non terminal INICIO;
non terminal CLASES,CLASE;
non terminal INSTRUCCION,INSTRUCCIONES;
non terminal IMPORT,METODO,DECLARACIONVARIABLES,ASIGNACIONVARIABLES;
non terminal SENTENCIAIF,SENTENCIAFOR,SENTENCIAWHILE,SENTENCIADOWHILE,SENTENCIASWITCH;
non terminal CONSOLA,BREAK,LLAMADA;
non terminal TIPO,EXPRESION,PARAMETROS,INSTRUCCIONESMETODO,INSTRUCCIONMETODO;
non terminal DECLARACIONFOR,CONTADOR,INCREMENTO;
non terminal CASOS,LISTAPARAMETROS;

//------> precedencia de menor a mayor

precedence left igualigual;
precedence left diferente;
precedence left menorque;
precedence left mayorque;
precedence left menorIgual;
precedence left mayorIgual;
precedence left AND;
precedence left OR;
precedence left NOT;
precedence left mas;
precedence left menos;
precedence left multiplicacion;
precedence left division;
precedence left potencia;
precedence left modulo;
precedence right id;








start with INICIO;

/*--------------- 3ra Area: Reglas Semanticas -----------------------*/

INICIO::= CLASES                                                                                {: :}
    ;
CLASES::= CLASES CLASE
    |CLASE
    ;
CLASES::= class_js id parentesisA parentesisC llaveabre INSTRUCCIONES llavecierra                      {: :}
    | class_js id llaveabre INSTRUCCIONES llavecierra
    ;


INSTRUCCIONES::=INSTRUCCIONES INSTRUCCION
    |INSTRUCCION
    ;


INSTRUCCION::=IMPORT
    |METODO
    |DECLARACIONVARIABLES
    |ASIGNACIONVARIABLES
    |SENTENCIAIF
    |SENTENCIAFOR   
    |SENTENCIAWHILE
    |SENTENCIADOWHILE
    |SENTENCIASWITCH
    |CONSOLA
    |BREAK
    |LLAMADA
    ;

IMPORT::= TIPO id igual require parentesisA EXPRESION parentesisC puntoycoma
    | TIPO id igual require parentesisA EXPRESION parentesisC
    ;

METODO::= id parentesisA PARAMETROS parentesisC llaveabre INSTRUCCIONESMETODO llavecierra
    | id parentesisA  parentesisC llaveabre INSTRUCCIONESMETODO llavecierra
    ;

PARAMETROS::= PARAMETROS coma id
    |id
    ;
INSTRUCCIONESMETODO::= INSTRUCCIONESMETODO INSTRUCCIONMETODO
    |INSTRUCCIONMETODO
    ;

INSTRUCCIONMETODO::= DECLARACIONVARIABLES
    |ASIGNACIONVARIABLES
    |SENTENCIAIF
    |SENTENCIAFOR   
    |SENTENCIAWHILE
    |SENTENCIADOWHILE
    |SENTENCIASWITCH
    |CONSOLA
    |BREAK
    |LLAMADA
    ;

DECLARACIONVARIABLES::= TIPO id igual EXPRESION puntoycoma
    |TIPO id igual EXPRESION
    |TIPO id puntoycoma
    |TIPO id igual id puntoycoma
    |TIPO id igual id
    |TIPO id 
    ;

EXPRESION::= EXPRESION igualigual EXPRESION 
    |EXPRESION diferente EXPRESION
    |EXPRESION menorque EXPRESION
    |EXPRESION mayorque EXPRESION
    |EXPRESION menorIgual EXPRESION
    |EXPRESION mayorIgual EXPRESION
    |EXPRESION AND EXPRESION
    |EXPRESION OR EXPRESION
    |NOT EXPRESION
    |EXPRESION mas EXPRESION
    |EXPRESION menos EXPRESION
    |EXPRESION multiplicacion EXPRESION
    |EXPRESION division EXPRESION
    |EXPRESION potencia EXPRESION
    |EXPRESION modulo EXPRESION
    |menos EXPRESION
    |true_js
    |false_js
    |cadena
    |numero
    |decimal
    |caracter
    ;

ASIGNACIONVARIABLES::= id igual EXPRESION puntoycoma
    |id igual EXPRESION
    ;

SENTENCIAIF::= if_js parentesisA EXPRESION parentesisC llaveabre INSTRUCCIONESMETODO llavecierra
    | if_js parentesisA EXPRESION parentesisC llaveabre INSTRUCCIONESMETODO llavecierra else_js SENTENCIAIF
    | if_js parentesisA EXPRESION parentesisC llaveabre INSTRUCCIONESMETODO llavecierra else_js llaveabre INSTRUCCIONESMETODO llavecierra
    ;

SENTENCIAFOR::= for_js parentesisA DECLARACIONFOR puntoycoma EXPRESION puntoycoma CONTADOR parentesisC llaveabre INSTRUCCIONESMETODO llavecierra
    ;

DECLARACIONFOR::= TIPO id igual EXPRESION
    | id igual EXPRESION
    ;

CONTADOR::= id INCREMENTO
    ;
INCREMENTO::= incrementoUno
    |decrementoUno
    |mas numero
    |menos numero
    ;

TIPO::= string_js
    |double_js
    |bool_js
    |int_js
    ;

SENTENCIAWHILE::= while_js parentesisA EXPRESION parentesisC llaveabre INSTRUCCIONESMETODO llavecierra
    ;

SENTENCIADOWHILE::= do_js llaveabre INSTRUCCIONESMETODO llavecierra while_js parentesisA EXPRESION parentesisC puntoycoma
    | do_js llaveabre INSTRUCCIONESMETODO llavecierra while_js parentesisA EXPRESION parentesisC 
    ;

SENTENCIASWITCH::= switch_js parentesisA EXPRESION parentesisC llaveabre CASOS llavecierra
    ;

CASOS::= case_js EXPRESION dospuntos INSTRUCCIONESMETODO
    ;

CONSOLA::=console_js punto log_js parentesisA EXPRESION parentesisC puntoycoma
    ;

BREAK::= break_js puntoycoma
    | break_js
    ;

LLAMADA::= id parentesisA parentesisC puntoycoma
    |id parentesisA parentesisC
    |id parentesisA LISTAPARAMETROS parentesisC puntoycoma
    |id parentesisA LISTAPARAMETROS parentesisC 
    ;

LISTAPARAMETROS::= LISTAPARAMETROS coma EXPRESION
    |EXPRESION
    ;