
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadoresJS;

import java_cup.runtime.Symbol;
import com.mycompany.proyecto1_2021s2.Ventana;
import com.mycompany.proyecto1_2021s2.errorJS;
import javax.swing.JOptionPane;
import java.util.LinkedList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class SintacticoJS extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return SimbolosJS.class;
}

  /** Default constructor. */
  @Deprecated
  public SintacticoJS() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public SintacticoJS(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public SintacticoJS(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\064\000\002\002\004\000\002\002\003\000\002\003" +
    "\006\000\002\004\004\000\002\004\003\000\002\005\003" +
    "\000\002\005\003\000\002\005\003\000\002\005\003\000" +
    "\002\005\003\000\002\006\011\000\002\007\006\000\002" +
    "\013\004\000\002\013\003\000\002\014\007\000\002\015" +
    "\003\000\002\015\003\000\002\016\003\000\002\016\003" +
    "\000\002\016\003\000\002\016\014\000\002\010\006\000" +
    "\002\012\006\000\002\011\006\000\002\017\007\000\002" +
    "\017\011\000\002\017\004\000\002\017\007\000\002\017" +
    "\007\000\002\017\006\000\002\017\010\000\002\017\006" +
    "\000\002\017\006\000\002\017\003\000\002\020\007\000" +
    "\002\020\007\000\002\020\006\000\002\020\006\000\002" +
    "\021\007\000\002\021\011\000\002\021\004\000\002\021" +
    "\006\000\002\021\010\000\002\021\003\000\002\023\010" +
    "\000\002\022\005\000\002\022\003\000\002\024\003\000" +
    "\002\024\003\000\002\024\003\000\002\024\003\000\002" +
    "\024\014" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\237\000\004\036\004\001\002\000\004\004\010\001" +
    "\002\000\004\002\000\001\002\000\004\002\007\001\002" +
    "\000\004\002\001\001\002\000\014\030\016\037\012\040" +
    "\013\041\024\043\014\001\002\000\016\005\ufffd\030\ufffd" +
    "\037\ufffd\040\ufffd\041\ufffd\043\ufffd\001\002\000\004\024" +
    "\234\001\002\000\004\004\203\001\002\000\004\004\152" +
    "\001\002\000\016\005\ufff8\030\ufff8\037\ufff8\040\ufff8\041" +
    "\ufff8\043\ufff8\001\002\000\004\004\052\001\002\000\016" +
    "\005\ufffa\030\ufffa\037\ufffa\040\ufffa\041\ufffa\043\ufffa\001" +
    "\002\000\016\005\ufffc\030\ufffc\037\ufffc\040\ufffc\041\ufffc" +
    "\043\ufffc\001\002\000\016\005\ufffb\030\ufffb\037\ufffb\040" +
    "\ufffb\041\ufffb\043\ufffb\001\002\000\016\005\ufff9\030\ufff9" +
    "\037\ufff9\040\ufff9\041\ufff9\043\ufff9\001\002\000\016\005" +
    "\051\030\016\037\012\040\013\041\024\043\014\001\002" +
    "\000\004\004\025\001\002\000\006\031\027\042\030\001" +
    "\002\000\010\005\041\031\037\042\040\001\002\000\004" +
    "\006\034\001\002\000\004\006\031\001\002\000\004\015" +
    "\032\001\002\000\004\007\033\001\002\000\010\005\uffdc" +
    "\031\uffdc\042\uffdc\001\002\000\004\016\035\001\002\000" +
    "\004\007\036\001\002\000\010\005\uffdd\031\uffdd\042\uffdd" +
    "\001\002\000\004\006\045\001\002\000\004\006\042\001" +
    "\002\000\016\005\uffeb\030\uffeb\037\uffeb\040\uffeb\041\uffeb" +
    "\043\uffeb\001\002\000\004\015\043\001\002\000\004\007" +
    "\044\001\002\000\010\005\uffde\031\uffde\042\uffde\001\002" +
    "\000\004\016\046\001\002\000\004\007\047\001\002\000" +
    "\010\005\uffdf\031\uffdf\042\uffdf\001\002\000\016\005\ufffe" +
    "\030\ufffe\037\ufffe\040\ufffe\041\ufffe\043\ufffe\001\002\000" +
    "\004\002\uffff\001\002\000\014\031\053\032\054\033\056" +
    "\034\060\035\057\001\002\000\004\006\147\001\002\000" +
    "\004\006\142\001\002\000\016\005\uffe0\031\uffe0\032\uffe0" +
    "\033\uffe0\034\uffe0\035\uffe0\001\002\000\004\006\135\001" +
    "\002\000\004\006\132\001\002\000\004\006\127\001\002" +
    "\000\016\005\067\031\063\032\062\033\056\034\066\035" +
    "\065\001\002\000\004\006\101\001\002\000\004\006\076" +
    "\001\002\000\016\005\uffe7\031\uffe7\032\uffe7\033\uffe7\034" +
    "\uffe7\035\uffe7\001\002\000\004\006\073\001\002\000\004" +
    "\006\070\001\002\000\016\005\uffec\030\uffec\037\uffec\040" +
    "\uffec\041\uffec\043\uffec\001\002\000\004\015\071\001\002" +
    "\000\004\007\072\001\002\000\016\005\uffe6\031\uffe6\032" +
    "\uffe6\033\uffe6\034\uffe6\035\uffe6\001\002\000\004\015\074" +
    "\001\002\000\004\007\075\001\002\000\016\005\uffe5\031" +
    "\uffe5\032\uffe5\033\uffe5\034\uffe5\035\uffe5\001\002\000\004" +
    "\016\077\001\002\000\004\007\100\001\002\000\016\005" +
    "\uffe9\031\uffe9\032\uffe9\033\uffe9\034\uffe9\035\uffe9\001\002" +
    "\000\004\027\102\001\002\000\014\011\105\014\104\015" +
    "\106\016\111\017\103\001\002\000\006\010\uffd2\026\uffd2" +
    "\001\002\000\006\010\uffd1\026\uffd1\001\002\000\004\004" +
    "\116\001\002\000\006\010\uffd0\026\uffd0\001\002\000\006" +
    "\010\112\026\113\001\002\000\006\010\uffd3\026\uffd3\001" +
    "\002\000\006\010\uffcf\026\uffcf\001\002\000\014\011\105" +
    "\014\104\015\106\016\111\017\103\001\002\000\004\007" +
    "\114\001\002\000\016\005\uffe8\031\uffe8\032\uffe8\033\uffe8" +
    "\034\uffe8\035\uffe8\001\002\000\006\010\uffd4\026\uffd4\001" +
    "\002\000\004\016\117\001\002\000\004\010\120\001\002" +
    "\000\004\015\121\001\002\000\004\010\122\001\002\000" +
    "\004\015\123\001\002\000\004\010\124\001\002\000\004" +
    "\015\125\001\002\000\004\005\126\001\002\000\006\010" +
    "\uffce\026\uffce\001\002\000\004\015\130\001\002\000\004" +
    "\007\131\001\002\000\016\005\uffe2\031\uffe2\032\uffe2\033" +
    "\uffe2\034\uffe2\035\uffe2\001\002\000\004\015\133\001\002" +
    "\000\004\007\134\001\002\000\016\005\uffe1\031\uffe1\032" +
    "\uffe1\033\uffe1\034\uffe1\035\uffe1\001\002\000\004\027\136" +
    "\001\002\000\014\011\105\014\104\015\106\016\111\017" +
    "\103\001\002\000\006\010\112\026\140\001\002\000\004" +
    "\007\141\001\002\000\016\005\uffd5\031\uffd5\032\uffd5\033" +
    "\uffd5\034\uffd5\035\uffd5\001\002\000\004\027\143\001\002" +
    "\000\014\011\105\014\104\015\106\016\111\017\103\001" +
    "\002\000\006\010\112\026\145\001\002\000\004\007\146" +
    "\001\002\000\016\005\uffe3\031\uffe3\032\uffe3\033\uffe3\034" +
    "\uffe3\035\uffe3\001\002\000\004\016\150\001\002\000\004" +
    "\007\151\001\002\000\016\005\uffe4\031\uffe4\032\uffe4\033" +
    "\uffe4\034\uffe4\035\uffe4\001\002\000\006\044\155\045\153" +
    "\001\002\000\004\016\ufff1\001\002\000\010\005\202\044" +
    "\155\045\153\001\002\000\004\016\ufff2\001\002\000\010" +
    "\005\ufff4\044\ufff4\045\ufff4\001\002\000\004\016\160\001" +
    "\002\000\004\025\161\001\002\000\012\011\165\014\162" +
    "\015\164\017\163\001\002\000\004\007\uffef\001\002\000" +
    "\004\007\uffee\001\002\000\004\007\ufff0\001\002\000\004" +
    "\004\170\001\002\000\004\007\167\001\002\000\010\005" +
    "\ufff3\044\ufff3\045\ufff3\001\002\000\004\016\171\001\002" +
    "\000\004\010\172\001\002\000\004\015\173\001\002\000" +
    "\004\010\174\001\002\000\004\015\175\001\002\000\004" +
    "\010\176\001\002\000\004\015\177\001\002\000\004\005" +
    "\200\001\002\000\004\007\uffed\001\002\000\010\005\ufff5" +
    "\044\ufff5\045\ufff5\001\002\000\016\005\ufff6\030\ufff6\037" +
    "\ufff6\040\ufff6\041\ufff6\043\ufff6\001\002\000\010\031\205" +
    "\032\204\033\056\001\002\000\004\006\227\001\002\000" +
    "\004\006\224\001\002\000\012\005\uffd6\031\uffd6\032\uffd6" +
    "\033\uffd6\001\002\000\012\005\213\031\211\032\210\033" +
    "\056\001\002\000\004\006\217\001\002\000\004\006\214" +
    "\001\002\000\012\005\uffd9\031\uffd9\032\uffd9\033\uffd9\001" +
    "\002\000\016\005\uffea\030\uffea\037\uffea\040\uffea\041\uffea" +
    "\043\uffea\001\002\000\004\016\215\001\002\000\004\007" +
    "\216\001\002\000\012\005\uffdb\031\uffdb\032\uffdb\033\uffdb" +
    "\001\002\000\004\027\220\001\002\000\014\011\105\014" +
    "\104\015\106\016\111\017\103\001\002\000\006\010\112" +
    "\026\222\001\002\000\004\007\223\001\002\000\012\005" +
    "\uffda\031\uffda\032\uffda\033\uffda\001\002\000\004\016\225" +
    "\001\002\000\004\007\226\001\002\000\012\005\uffd8\031" +
    "\uffd8\032\uffd8\033\uffd8\001\002\000\004\027\230\001\002" +
    "\000\014\011\105\014\104\015\106\016\111\017\103\001" +
    "\002\000\006\010\112\026\232\001\002\000\004\007\233" +
    "\001\002\000\012\005\uffd7\031\uffd7\032\uffd7\033\uffd7\001" +
    "\002\000\004\015\235\001\002\000\004\010\236\001\002" +
    "\000\004\015\237\001\002\000\004\023\240\001\002\000" +
    "\004\007\241\001\002\000\016\005\ufff7\030\ufff7\037\ufff7" +
    "\040\ufff7\041\ufff7\043\ufff7\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\237\000\006\002\005\003\004\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\020\004\022\005\010\006\017\007\020\010\016\011" +
    "\021\012\014\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\016\005\047\006\017\007" +
    "\020\010\016\011\021\012\014\001\001\000\002\001\001" +
    "\000\004\020\025\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\017\060\023" +
    "\054\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\023\063\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\022\106\024\107\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\024\114\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\022\136\024\107" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\022\143\024\107\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\013\153\014\155\015\156\001\001\000\002\001\001\000" +
    "\006\014\200\015\156\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\016" +
    "\165\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\021\206\023\205\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\023\211\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\022\220\024\107\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\022\230" +
    "\024\107\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$SintacticoJS$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$SintacticoJS$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$SintacticoJS$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




        public void syntax_error(Symbol s)
        {
            System.err.println("Error en la Linea " + (s.right+1) +" Columna "+(s.left+1)+ ". Identificador "+s.value + " no reconocido. Se ha recuperado del error." );
            errorJS nuevo = new errorJS("Error Sintactico (Recuperado)", s.value.toString(), s.right+1, s.left+1);
            Ventana.listaErrores2.add(nuevo);
        }
        public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
        {
            System.err.println("Error en la Linea " + (s.right+1)+ " Columna "+(s.left+1)+". Identificador " +s.value + " no reconocido.");
            errorJS nuevo = new errorJS("Error Sintactico", s.value.toString(), s.right+1, s.left+1);
            Ventana.listaErrores2.add(nuevo);
        }

 

/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$SintacticoJS$actions {

  
  private final SintacticoJS parser;

  /** Constructor */
  CUP$SintacticoJS$actions(SintacticoJS parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$SintacticoJS$do_action_part00000000(
    int                        CUP$SintacticoJS$act_num,
    java_cup.runtime.lr_parser CUP$SintacticoJS$parser,
    java.util.Stack            CUP$SintacticoJS$stack,
    int                        CUP$SintacticoJS$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$SintacticoJS$result;

      /* select the action based on the action number */
      switch (CUP$SintacticoJS$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-1)).value;
		RESULT = start_val;
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$SintacticoJS$parser.done_parsing();
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= GENERARREPORTE 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // GENERARREPORTE ::= generarReporteEstadistico llaveabre INSTRUCCIONES llavecierra 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("GENERARREPORTE",1, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // INSTRUCCIONES ::= INSTRUCCIONES INSTRUCCION 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",2, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // INSTRUCCIONES ::= INSTRUCCION 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",2, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // INSTRUCCION ::= COMPARE 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",3, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // INSTRUCCION ::= DEFINIRGLOBALES 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",3, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // INSTRUCCION ::= GRAFICABARRAS 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",3, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // INSTRUCCION ::= GRAFICAPIE 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",3, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // INSTRUCCION ::= GRAFICASLINEAS 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",3, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // COMPARE ::= compare parentesisA cadena coma cadena parentesisC puntoycoma 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("COMPARE",4, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-6)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // DEFINIRGLOBALES ::= DefinirGlobales llaveabre DEFINICIONVARIABLESG llavecierra 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("DEFINIRGLOBALES",5, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // DEFINICIONVARIABLESG ::= DEFINICIONVARIABLESG DEFINICIONVARIABLEG 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("DEFINICIONVARIABLESG",9, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // DEFINICIONVARIABLESG ::= DEFINICIONVARIABLEG 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("DEFINICIONVARIABLESG",9, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // DEFINICIONVARIABLEG ::= TIPO id igual VALORTIPO puntoycoma 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("DEFINICIONVARIABLEG",10, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-4)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // TIPO ::= string 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("TIPO",11, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // TIPO ::= dou 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("TIPO",11, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // VALORTIPO ::= cadena 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("VALORTIPO",12, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // VALORTIPO ::= numero 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("VALORTIPO",12, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // VALORTIPO ::= decimal 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("VALORTIPO",12, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // VALORTIPO ::= dolar llaveabre id coma cadena coma cadena coma cadena llavecierra 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("VALORTIPO",12, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-9)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // GRAFICABARRAS ::= graficaBarras llaveabre INFOSBARRAS llavecierra 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("GRAFICABARRAS",6, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // GRAFICASLINEAS ::= graficaLineas llaveabre INFOSLINEAS llavecierra 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("GRAFICASLINEAS",8, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // GRAFICAPIE ::= graficaPie llaveabre INFOS llavecierra 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("GRAFICAPIE",7, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // INFOSBARRAS ::= INFOSBARRAS titulo dospuntos id puntoycoma 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INFOSBARRAS",13, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-4)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // INFOSBARRAS ::= INFOSBARRAS ejeX dospuntos corcheteA DATOS corcheteC puntoycoma 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INFOSBARRAS",13, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-6)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // INFOSBARRAS ::= INFOSBARRAS VALORES 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INFOSBARRAS",13, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // INFOSBARRAS ::= INFOSBARRAS tituloX dospuntos cadena puntoycoma 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INFOSBARRAS",13, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-4)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // INFOSBARRAS ::= INFOSBARRAS tituloY dospuntos cadena puntoycoma 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INFOSBARRAS",13, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-4)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // INFOSBARRAS ::= titulo dospuntos id puntoycoma 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INFOSBARRAS",13, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // INFOSBARRAS ::= ejeX dospuntos corcheteA DATOS corcheteC puntoycoma 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INFOSBARRAS",13, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-5)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // INFOSBARRAS ::= tituloX dospuntos cadena puntoycoma 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INFOSBARRAS",13, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // INFOSBARRAS ::= tituloY dospuntos cadena puntoycoma 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INFOSBARRAS",13, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // INFOSBARRAS ::= VALORES 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INFOSBARRAS",13, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // INFOSLINEAS ::= INFOSLINEAS titulo dospuntos id puntoycoma 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INFOSLINEAS",14, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-4)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // INFOSLINEAS ::= INFOSLINEAS ar dospuntos cadena puntoycoma 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INFOSLINEAS",14, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-4)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // INFOSLINEAS ::= titulo dospuntos id puntoycoma 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INFOSLINEAS",14, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // INFOSLINEAS ::= ar dospuntos cadena puntoycoma 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INFOSLINEAS",14, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // INFOS ::= INFOS titulo dospuntos id puntoycoma 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INFOS",15, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-4)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // INFOS ::= INFOS ejeX dospuntos corcheteA DATOS corcheteC puntoycoma 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INFOS",15, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-6)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // INFOS ::= INFOS VALORES 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INFOS",15, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // INFOS ::= titulo dospuntos id puntoycoma 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INFOS",15, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // INFOS ::= ejeX dospuntos corcheteA DATOS corcheteC puntoycoma 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INFOS",15, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-5)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // INFOS ::= VALORES 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("INFOS",15, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // VALORES ::= Valores dospuntos corcheteA DATOS corcheteC puntoycoma 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("VALORES",17, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-5)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // DATOS ::= DATOS coma DATO 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("DATOS",16, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-2)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // DATOS ::= DATO 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("DATOS",16, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // DATO ::= decimal 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("DATO",18, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // DATO ::= numero 
            {
              Object RESULT =null;

              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("DATO",18, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // DATO ::= cadena 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("DATO",18, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // DATO ::= id 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("DATO",18, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // DATO ::= dolar llaveabre id coma cadena coma cadena coma cadena llavecierra 
            {
              Object RESULT =null;
		 
              CUP$SintacticoJS$result = parser.getSymbolFactory().newSymbol("DATO",18, ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.elementAt(CUP$SintacticoJS$top-9)), ((java_cup.runtime.Symbol)CUP$SintacticoJS$stack.peek()), RESULT);
            }
          return CUP$SintacticoJS$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$SintacticoJS$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$SintacticoJS$do_action(
    int                        CUP$SintacticoJS$act_num,
    java_cup.runtime.lr_parser CUP$SintacticoJS$parser,
    java.util.Stack            CUP$SintacticoJS$stack,
    int                        CUP$SintacticoJS$top)
    throws java.lang.Exception
    {
              return CUP$SintacticoJS$do_action_part00000000(
                               CUP$SintacticoJS$act_num,
                               CUP$SintacticoJS$parser,
                               CUP$SintacticoJS$stack,
                               CUP$SintacticoJS$top);
    }
}

}
